// /functions/[[path]].js
// Reihenfolge:
// 1) Eigene 301 (EXACT, dann PREFIX) -> sofort redirect
// 2) Pages laufen lassen (statische Dateien + _redirects)
// 3) Wenn 404: 410 (EXACT, dann PREFIX, dann global außerhalb Sprachpfade)
// Robust gg. Slashes & Tippfehler, mit X-Debug-Header zur Diagnose.

const LANG_ROOTS = ["/en", "/de/", "/th/"];

function normPath(raw) {
  // strip query/hash, compress //, trim, remove trailing slash (außer '/', '/en/', '/de/', '/th/')
  let p = raw.split("?")[0].split("#")[0].replace(/\/{2,}/g, "/").trim();
  if (p === "/") return "/";
  if (LANG_ROOTS.includes(p)) return p;
  return p.replace(/\/+$/, "");
}

function ensureLeadingSlash(p) {
  return p.startsWith("/") ? p : `/${p}`;
}

function joinUrl(base, suffix) {
  if (!suffix || suffix === "/") return base;
  const b = base.replace(/\/+$/, "");
  const s = suffix.replace(/^\/+/, "");
  return `${b}/${s}`;
}

// --- Root-Dateien, die auch außerhalb Sprachpfaden 200 sein dürfen ---
const ROOT_FILES = new Set([
  "/", "/style.css", "/robots.txt", "/sitemap.xml", "/sitemap-images.xml",
  "/site.webmanifest", "/favicon.ico", "/favicon.svg", "/404.html"
]);

function isAsset(path) {
  return (
    path.startsWith("/img/") || path.startsWith("/images/") ||
    path.startsWith("/css/") || path.startsWith("/js/") ||
    path.startsWith("/fonts/") || path.startsWith("/docs/") ||
    path.startsWith("/.well-known/") || ROOT_FILES.has(path) ||
    path.startsWith("/favicon") // z. B. /favicon-32x32.png
  );
}

function isInLang(path) {
  return path === "/" || LANG_ROOTS.some(pre => path.startsWith(pre));
}

// --------------------- 301 REDIRECT LISTEN ---------------------
// 👉 Pflege HIER: from ohne/mit Slash egal – wird normalisiert.
//    to am besten mit Slash (außer zielt auf Datei .pdf/.jpg/.html etc.).

// 1) EXAKTE 301 — als Paare [from, to]
const REDIRECTS_EXACT_RAW = [
  // BEISPIEL (aus deinem Test):
  ["/da/about", "/de/about/"],
  ["/de", "/de/"],
  ["/de/2025/04", "/de/posts/"],
  ["/de/2025/05", "/de/posts/"],
  ["/de/about", "/de/about/"],
  ["/de/about-search-recovery", "/de/posts/scuba-knowledge/about-search-recovery/"],
  ["/de/about-underwater-photography", "/de/posts/tips-and-tricks/about-underwater-photography/"],
  ["/de/about-us", "/de/about/"],
  ["/de/about/stornierung-und-rueckersattung", "/de/refund-policy/"],
  ["/de/agbs", "/de/terms-and-conditions/"],
  ["/de/anreise", "/de/faqs/faq-getting-here-accommodation/"],
  ["/de/apeks-dst4", "/de/store/category/equipment/"],
  ["/de/apeks-xtx-atemregulator-ueberblick", "/de/store/category/equipment/"],
  ["/de/apeks-xtx", "/de/store/category/equipment/"],
  ["/de/barrakudas-koh-chang", "/de/posts/marine-life-koh-chang/marine-life-barracuda/"],
  ["/de/best-dive-computers", "/de/posts/scuba-knowledge/best-dive-computers/"],
  ["/de/blogs", "/de/posts/"],
  ["/de/contact", "/de/contact/"],
  ["/de/das-taucher-logbuch", "/de/posts/scuba-knowledge/dive-logbook/"],
  ["/de/deep-diving", "/de/posts/tips-and-tricks/deep-diving/"],
  ["/de/der-weg-eines-sport-tauchers", "/de/posts/straight-talk/dive-professional-training/"],
  ["/de/die-10-beliebtesten-tauchaktivitaeten-auf-koh-chang-chang-diving-center", "/de/posts/tips-and-tricks/diving-activities/"],
  ["/de/die-besten-tauchcomputer-2025", "/de/posts/scuba-knowledge/best-dive-computers/"],
  ["/de/die-meerestiere-von-koh-chang-asianisches-pazifikum", "/de/posts/marine-life-koh-chang/"],
  ["/de/dive-professional-training", "/de/posts/straight-talk/dive-professional-training/"],
  ["/de/dive-sites", "/de/dive-sites/"],
  ["/de/dive-sites/blueberry-hill", "/de/dive-sites/blueberry-hill/"],
  ["/de/dive-sites/dive-site-map-koh-chang", "/de/dive-sites/dive-site-map-koh-chang/"],
  ["/de/dive-sites/hin-luk-bat", "/de/dive-sites/hin-luk-bat/"],
  ["/de/dive-sites/hin-pray-nam", "/de/dive-sites/hin-pray-nam/"],
  ["/de/dive-sites/hin-raab-north", "/de/dive-sites/hin-raab-north/"],
  ["/de/dive-sites/hin-raab-south", "/de/dive-sites/hin-raab-south/"],
  ["/de/dive-sites/hin-rua-tek", "/de/dive-sites/hin-rua-tek/"],
  ["/de/dive-sites/hin-sam-sao", "/de/dive-sites/hin-sam-sao/"],
  ["/de/dive-sites/htms-chang-wreck", "/de/dive-sites/htms-chang-wreck/"],
  ["/de/dive-sites/koh-rang-pinnacle", "/de/dive-sites/koh-rang-pinnacle/"],
  ["/de/dive-sites/koho-maru-5", "/de/dive-sites/koho-maru-5/"],
  ["/de/dive-sites/phutthayotfa-chulalok-wrack-koh-chang", "/de/dive-sites/phutthayotfa-chulalok-wreck-koh-chang/"],
  ["/de/dive-sites/phutthayotfa-chulalok-wreck-koh-chang", "/de/dive-sites/phutthayotfa-chulalok-wreck-koh-chang/"],
  ["/de/dive-sites/secret-reef", "/de/dive-sites/secret-reef/"],
  ["/de/dive-sites/t11-wreck", "/de/dive-sites/t11-wreck/"],
  ["/de/diving-myths", "/de/posts/straight-talk/diving-myths/"],
  ["/de/faqs", "/de/faqs/"],
  ["/de/faqs/faq-allgemeine-fragen-koh-chang", "/de/faqs/faq-general-questions-koh-chang/"],
  ["/de/faqs/faq-anreise-unterkunft-koh-chang", "/de/faqs/faq-getting-here-accommodation/"],
  ["/de/faqs/faq-diving-health-safety-thailand", "/de/faqs/faq-diving-health-safety-thailand/"],
  ["/de/faqs/faq-general-questions-koh-chang", "/de/faqs/faq-general-questions-koh-chang/"],
  ["/de/faqs/faq-getting-here-accommodation", "/de/faqs/faq-getting-here-accommodation/"],
  ["/de/faqs/faq-schnuppertauchen-fun-dives-koh-chang", "/de/faqs/faq-try-dive-fun-dives-koh-chang/"],
  ["/de/faqs/faq-tauchen-koh-chang", "/de/faqs/faq-diving-koh-chang/"],
  ["/de/faqs/getting-here-accommodation-frequently-asked-questions", "/de/faqs/faq-getting-here-accommodation/"],
  ["/de/faqs/hotels-in-der-naehe-der-tauchbasis", "/de/faqs/faq-getting-here-accommodation/"],
  ["/de/faqs/kreditkarten-zahlung", "/de/faqs/faq-booking-payment-scuba-koh-chang/"],
  ["/de/faqs/medizinischer-fragebogen-fuer-taucher", "/de/faqs/faq-diving-health-safety-thailand/"],
  ["/de/faqs/sollte-ich-vorab-buchen", "/de/faqs/faq-booking-payment-scuba-koh-chang/"],
  ["/de/faqs/tauchen-als-brillentraeger", "/de/faqs/faq-diving-health-safety-thailand/"],
  ["/de/faqs/wann-ist-die-beste-tauchzeit-auf-koh-chang-und-was-erwartet-mich", "/de/faqs/faq-general-questions-koh-chang/"],
  ["/de/faqs/was-ist-die-beste-moeglichkeit-geld-nach-thailand-zu-ueberweisen", "/de/faqs/faq-booking-payment-scuba-koh-chang/"],
  ["/de/faqs/wie-komme-ich-zur-tauchbasis", "/de/faqs/faq-getting-here-accommodation/"],
  ["/de/faqs/wo-befindet-sich-die-tauchbasis", "/de/faqs/faq-getting-here-accommodation/"],
  ["/de/forms", "/de/posts/"],
  ["/de/funktion-der-ersten-stufe-apeks-dst", "/de/posts/"],
  ["/de/gasverbrauch-beim-tauchen", "/de/posts/scuba-knowledge/gas-consumption/"],
  ["/de/geschaeftsbedingungen", "/de/terms-and-conditions/"],
  ["/de/getting-to-koh-chang", "/de/faqs/faq-getting-here-accommodation/"],
  ["/de/gruene-meeresschildkroete-koh-chang", "/de/posts/marine-life-koh-chang/marine-life-green-sea-turtle/"],
  ["/de/home", "/de/"],
  ["/de/how-to-advanced-course", "/de/posts/diving-how-to-guides-koh-chang/how-to-advanced-course/"],
  ["/de/how-to-fun-dives", "/de/posts/diving-how-to-guides-koh-chang/how-to-fun-dives/"],
  ["/de/how-to-master-scuba-diver", "/de/posts/diving-how-to-guides-koh-chang/how-to-master-scuba-diver/"],
  ["/de/how-to-open-advanced", "/de/posts/diving-how-to-guides-koh-chang/how-to-open-advanced/"],
  ["/de/how-to-rescue-diver", "/de/posts/diving-how-to-guides-koh-chang/how-to-rescue-diver/"],
  ["/de/how-to-specialty-courses", "/de/posts/diving-how-to-guides-koh-chang/how-to-specialty-courses/"],
  ["/de/how-to-try-dive", "/de/posts/diving-how-to-guides-koh-chang/"],
  ["/de/how-we-run-your-diving-course-or-day-trip", "/de/posts/diving-how-to-guides-koh-chang/"],
  ["/de/index.html", "/de/"],
  ["/de/koh-chang-reisefuehrer", "/de/posts/koh-chang-diving-travel-guides/travel-guide/"],
  ["/de/kontakt", "/de/contact/"],
  ["/de/Kategorie/chang-diving-blog", "/de/posts/"],
  ["/de/Kategorie/tauchblog", "/de/posts/"],
  ["/de/Kategorie/tauchtips", "/de/posts/tips-and-tricks/"],
  ["/de/Kategorie/tipps-und-tricks", "/de/posts/tips-and-tricks/"],
  ["/de/Kategorie/tauchen", "/de/posts/"],
  ["/de/Kategorie/taucher-wissen", "/de/posts/scuba-knowledge/"],
  ["/de/Kategorie/tech-tattoos", "/de/posts/tips-and-tricks/"],
  ["/de/Kategorie/travel-stories", "/de/posts/koh-chang-diving-travel-guides/"],
  ["/de/Kategorie/videos", "/de/posts/"],
  ["/de/kurse/advanced-open-water", "/de/product/advanced/"],
  ["/de/kurse/divemaster", "/de/product/divemaster/"],
  ["/de/luftverbrauch-beim-sport-tauchen", "/de/posts/scuba-knowledge/gas-consumption/"],
  ["/de/marine-life-barracuda", "/de/posts/marine-life-koh-chang/marine-life-barracuda/"],
  ["/de/marine-life-batfish", "/de/posts/marine-life-koh-chang/marine-life-batfish/"],
  ["/de/marine-life-blacktip-reef-shark", "/de/posts/marine-life-koh-chang/marine-life-blacktip-reef-shark/"],
  ["/de/marine-life-green-sea-turtle", "/de/posts/marine-life-koh-chang/marine-life-green-sea-turtle/"],
  ["/de/marine-life-nudibranch", "/de/posts/marine-life-koh-chang/marine-life-nudibranch/"],
  ["/de/marine-life-titan-triggerfish", "/de/posts/marine-life-koh-chang/marine-life-titan-triggerfish/"],
  ["/de/marine-life-whale-shark", "/de/posts/marine-life-koh-chang/marine-life-whale-shark/"],
  ["/de/marine-life", "/de/posts/marine-life-koh-chang/"],
  ["/de/nitrox-info", "/de/posts/scuba-knowledge/nitrox-info/"],
  ["/de/padi-vs-sdi-tdi-welches-tauchausbildungssystem-passt-zu-dir", "/de/posts/straight-talk/padi-vs-sdi-tdi/"],
  ["/de/pirm-udom-sub-nachhaltiges-tauchen-auf-koh-chang", "/de/posts/straight-talk/sustainable-diving/"],
  ["/de/posts", "/de/posts/"],
  ["/de/posts/diving-how-to-guides-koh-chang", "/de/posts/diving-how-to-guides-koh-chang/"],
  ["/de/posts/diving-how-to-guides-koh-chang/how-to-advanced-course", "/de/posts/diving-how-to-guides-koh-chang/how-to-advanced-course/"],
  ["/de/posts/diving-how-to-guides-koh-chang/how-to-rescue-diver", "/de/posts/diving-how-to-guides-koh-chang/how-to-rescue-diver/"],
  ["/de/posts/diving-how-to-guides-koh-chang/how-to-scuba-review", "/de/posts/diving-how-to-guides-koh-chang/how-to-scuba-review/"],
  ["/de/posts/koh-chang-diving-travel-guides", "/de/posts/koh-chang-diving-travel-guides/"],
  ["/de/posts/marine-life-koh-chang", "/de/posts/marine-life-koh-chang/"],
  ["/de/posts/marine-life-koh-chang/marine-life-blacktip-reef-shark", "/de/posts/marine-life-koh-chang/marine-life-blacktip-reef-shark/"],
  ["/de/posts/marine-life-koh-chang/marine-life-titan-triggerfish", "/de/posts/marine-life-koh-chang/marine-life-titan-triggerfish/"],
  ["/de/posts/scuba-knowledge/about-search-recovery", "/de/posts/scuba-knowledge/about-search-recovery/"],
  ["/de/posts/scuba-knowledge/best-dive-computers", "/de/posts/scuba-knowledge/best-dive-computers/"],
  ["/de/posts/scuba-knowledge/dive-logbook", "/de/posts/scuba-knowledge/dive-logbook/"],
  ["/de/posts/scuba-knowledge/gas-consumption", "/de/posts/scuba-knowledge/gas-consumption/"],
  ["/de/posts/scuba-knowledge/safety-check", "/de/posts/scuba-knowledge/safety-check/"],
  ["/de/posts/scuba-knowledge/wreck-diving-koh-chang", "/de/posts/scuba-knowledge/wreck-diving-koh-chang/"],
  ["/de/posts/straight-talk", "/de/posts/straight-talk/"],
  ["/de/posts/straight-talk/diving-myths", "/de/posts/straight-talk/diving-myths/"],
  ["/de/posts/straight-talk/diving-social-media", "/de/posts/straight-talk/diving-social-media/"],
  ["/de/posts/straight-talk/ozean-und-klima", "/de/posts/straight-talk/ocean-climate/"],
  ["/de/posts/straight-talk/padi-vs-sdi-tdi", "/de/posts/straight-talk/padi-vs-sdi-tdi/"],
  ["/de/posts/tipps-und-tricks/tauchaktivitaeten", "/de/posts/tips-and-tricks/diving-activities/"],
  ["/de/posts/tips-and-tricks/about-underwater-photography", "/de/posts/tips-and-tricks/about-underwater-photography/"],
  ["/de/posts/tips-and-tricks/deep-diving", "/de/posts/tips-and-tricks/deep-diving/"],
  ["/de/preise", "/de/prices/"],
  ["/de/prices", "/de/prices/"],
  ["/de/privacy-policy", "/de/privacy-policy/"],
  ["/de/product/advanced", "/de/product/advanced/"],
  ["/de/product/advanced-nitrox", "/de/product/advanced-nitrox/"],
  ["/de/product/advanced-wreck", "/de/product/advanced-wreck/"],
  ["/de/product/advanced-wreck-diver", "/de/product/advanced-wreck/"],
  ["/de/product/apeks-backplate", "/de/store/category/equipment/"],
  ["/de/product/apeks-black-ice", "/de/store/category/equipment/"],
  ["/de/product/apeks-bungee-connector-kit", "/de/store/category/equipment/"],
  ["/de/product/apeks-dry75-rucksack", "/de/store/category/equipment/"],
  ["/de/product/apeks-line-markers", "/de/store/category/equipment/"],
  ["/de/product/apeks-mtx-r-octopus", "/de/store/category/equipment/"],
  ["/de/product/apeks-mtx-r-regulator-set", "/de/store/category/equipment/"],
  ["/de/product/apeks-mtx-r", "/de/store/category/equipment/"],
  ["/de/product/apeks-mtx-rc-regulator-set", "/de/store/category/equipment/"],
  ["/de/product/apeks-pressure-gauge", "/de/store/category/equipment/"],
  ["/de/product/apeks-regulator-service", "/de/store/category/equipment/"],
  ["/de/product/apeks-single-tank-adapter", "/de/store/category/equipment/"],
  ["/de/product/apeks-single-tank-adaptor", "/de/store/category/equipment/"],
  ["/de/product/apeks-single-tank-wing-set-wtx-d", "/de/store/category/equipment/"],
  ["/de/product/apeks-spools-lifeline", "/de/store/category/equipment/"],
  ["/de/product/apeks-surface-marker-buoy", "/de/store/category/equipment/"],
  ["/de/product/apeks-tech-shorts", "/de/store/category/equipment/"],
  ["/de/product/apeks-tek3-regulator", "/de/store/category/equipment/"],
  ["/de/product/apeks-vx1-mask", "/de/store/category/equipment/"],
  ["/de/product/apeks-vx1-maske", "/de/store/category/equipment/"],
  ["/de/product/apeks-wetnotes", "/de/store/category/equipment/"],
  ["/de/product/apeks-wsx-sidemount-harness", "/de/store/category/equipment/"],
  ["/de/product/apeks-wtx-deluxe-harness", "/de/store/category/equipment/"],
  ["/de/product/apeks-xl-4-regulator-set", "/de/store/category/equipment/"],
  ["/de/product/apeks-xl-4-set", "/de/store/category/equipment/"],
  ["/de/product/apeks-xl4-nitrox", "/de/store/category/equipment/"],
  ["/de/product/apeks-xl4-octopus", "/de/store/category/equipment/"],
  ["/de/product/apeks-xl4", "/de/store/category/equipment/"],
  ["/de/product/apeks-xtx40-nitrox-regulator", "/de/store/category/equipment/"],
  ["/de/product/apeks-xtx50", "/de/store/category/equipment/"],
  ["/de/product/auffrischungskurs", "/de/store/category/equipment/"],
  ["/de/product/deco-procedures", "/de/product/deco-procedures/"],
  ["/de/product/deep-blue-dry-bags", "/de/store/category/equipment/"],
  ["/de/product/deep-blue-speed3-snorkel-fin", "/de/store/category/equipment/"],
  ["/de/product/deep-blue-xtreme-mask", "/de/store/category/equipment/"],
  ["/de/product/deep-diver", "/de/product/deep-diver/"],
  ["/de/product/deep-wreck-nitrox", "/de/product/deep-wreck-nitrox/"],
  ["/de/product/der-advanced-open-water-diver-kurs", "/de/product/advanced/"],
  ["/de/product/der-divemaster-kurs", "/de/product/divemaster/"],
  ["/de/product/der-open-water-diver-kurs", "/de/product/open-water-diver/"],
  ["/de/product/der-rescue-diver-kurs", "/de/product/rescue-diver/"],
  ["/de/product/der-sdi-solo-diver-kurs", "/de/product/solo-diver/"],
  ["/de/product/discover-scuba-diving", "/de/product/try-dive/"],
  ["/de/product/divemaster", "/de/product/divemaster/"],
  ["/de/product/efr-instructor", "/de/product/efr-instructor/"],
  ["/de/product/emergency-first-response-instructor-course-efri-course", "/de/product/efr-instructor/"],
  ["/de/product/first-aid", "/de/product/first-aid/"],
  ["/de/product/fun-dives", "/de/product/fun-dives/"],
  ["/de/product/fun-dives-koh-chang", "/de/product/fun-dives/"],
  ["/de/product/fun-dives-koh-chang", "/de/product/fun-dives/"],
  ["/de/product/go-sport-fin", "/de/store/category/equipment/"],
  ["/de/product/go-travel-fin-2", "/de/store/category/equipment/"],
  ["/de/product/go-travel-fin", "/de/store/category/equipment/"],
  ["/de/product/hybrid-cargo-shorts", "/de/store/category/equipment/"],
  ["/de/product/instructor-crossover", "/de/product/instructor-crossover/"],
  ["/de/product/insurance", "/de/product/insurance/"],
  ["/de/product/intro-to-tech", "/de/product/intro-to-tech/"],
  ["/de/product/master-scuba-diver", "/de/product/master-scuba-diver/"],
  ["/de/product/miete-eine-gopro-hero-7-black", "/de/product/rent-gopro/"],
  ["/de/product/navigation", "/de/product/navigation/"],
  ["/de/product/night", "/de/product/night/"],
  ["/de/product/nitrox-diver", "/de/product/nitrox-diver/"],
  ["/de/product/open-advanced-package", "/de/product/open-advanced-package/"],
  ["/de/product/open-to-divemaster", "/de/product/open-to-divemaster/"],
  ["/de/product/open-water-diver", "/de/product/open-water-diver/"],
  ["/de/product/open-water-diver-referral-kurs", "/de/product/open-water-diver/"],
  ["/de/product/open-water-diver-to-divemaster", "/de/product/open-to-divemaster/"],
  ["/de/product/rent-gopro", "/de/product/rent-gopro/"],
  ["/de/product/rescue-diver", "/de/product/rescue-diver/"],
  ["/de/product/s-tek-donut-wing", "/de/store/category/equipment/"],
  ["/de/product/s-tek-pure-tek-harness", "/de/store/category/equipment/"],
  ["/de/product/schnorcheln-auf-koh-chang-erkunde-die-unterwasserwelt-mit-unserem-tauchboot", "/de/product/snorkeling/"],
  ["/de/product/schnorcheln-gehen-in-koh-chang", "/de/product/snorkeling/"],
  ["/de/product/scuba-review", "/de/product/scuba-review/"],
  ["/de/product/scubapro-backplate", "/de/store/category/equipment/"],
  ["/de/product/scubapro-finimeter", "/de/store/category/equipment/"],
  ["/de/product/scubapro-mash-bag", "/de/store/category/equipment/"],
  ["/de/product/scubapro-mk-25-evo-s600-set", "/de/store/category/equipment/"],
  ["/de/product/scubapro-mk21-c370-set", "/de/store/category/equipment/"],
  ["/de/product/scubapro-mk21-c370", "/de/store/category/equipment/"],
  ["/de/product/scubapro-pressure-gauge", "/de/store/category/equipment/"],
  ["/de/product/scubapro-single-tank-adapter-sta", "/de/store/category/equipment/"],
  ["/de/product/scubapro-solo-mask", "/de/store/category/equipment/"],
  ["/de/product/scubapro-x-tek-donut-wing", "/de/store/category/equipment/"],
  ["/de/product/scubapro-x-tek-sidemount", "/de/store/category/equipment/"],
  ["/de/product/scubapro-x-tek-wing-set", "/de/store/category/equipment/"],
  ["/de/product/sdi-idc", "/de/product/sdi-idc/"],
  ["/de/product/sdi-ie", "/de/product/sdi-ie/"],
  ["/de/product/sdi-instructor-development-course-idc", "/de/product/sdi-idc/"],
  ["/de/product/search-recovery", "/de/product/search-recovery/"],
  ["/de/product/sidemount", "/de/product/sidemount/"],
  ["/de/product/snorkeling", "/de/product/snorkeling/"],
  ["/de/product/solo-diver", "/de/product/solo-diver/"],
  ["/de/product/spass-tauchgaenge", "/de/product/fun-dives/"],
  ["/de/product/spezialkurs-nachttauchen", "/de/product/night/"],
  ["/de/product/suunto-d4i-novo", "/de/store/category/equipment/"],
  ["/de/product/suunto-d5", "/de/store/category/equipment/"],
  ["/de/product/suunto-zoop-novo", "/de/store/category/equipment/"],
  ["/de/product/tdi-advanced-nitrox-taucher", "/de/product/advanced-nitrox/"],
  ["/de/product/tdi-advanced-wrack-taucher", "/de/product/advanced-wreck/"],
  ["/de/product/tech-package", "/de/product/tech-package/"],
  ["/de/product/tief-wrack-nitrox-paket", "/de/product/nitrox-diver/"],
  ["/de/product/try-dive", "/de/product/try-dive/"],
  ["/de/product/versicherung", "/de/product/insurance/"],
  ["/de/product/wreck-diver", "/de/product/wreck-diver/"],
  ["/de/product/wtx-d-single-donut-wing", "/de/store/category/equipment/"],
  ["/de/product/x-tek-pure-tek-harness", "/de/store/category/equipment/"],
  ["/de/produkt/advanced", "/de/product/advanced/"],
  ["/de/produkt/try-dive", "/de/product/try-dive/"],
  ["/de/reel-and-guideline-use", "/de/posts/tips-and-tricks/reel-guideline/"],
  ["/de/refund-policy", "/de/refund-policy/"],
  ["/de/schwarzspitzen-riffhaie-koh-chang", "/de/posts/marine-life-koh-chang/marine-life-blacktip-reef-shark/"],
  ["/de/smb-guide", "/de/posts/scuba-knowledge/smb-guide/"],
  ["/de/so-laeuft-der-open-water-diver-kurs-bei-chang-diving-ab-schritt-fuer-schritt-2025-koh-chang", "/de/posts/diving-how-to-guides-koh-chang/how-to-open-water-course/"],
  ["/de/store", "/de/store/"],
  ["/de/store/category", "/de/store/category/"],
  ["/de/store/category/courses", "/de/store/category/courses/"],
  ["/de/store/category/Courses", "/de/store/category/courses/"],
  ["/de/store/category/courses/advanced-courses", "/de/store/category/courses/advanced-courses/"],
  ["/de/store/category/courses/beginner-courses", "/de/store/category/courses/beginner-courses/"],
  ["/de/store/category/courses/fortgeschrittenen-kurse", "/de/store/category/courses/advanced-courses/"],
  ["/de/store/category/courses/professional-courses", "/de/store/category/courses/professional-courses/"],
  ["/de/store/category/courses/speciality", "/de/store/category/courses/speciality/"],
  ["/de/store/category/courses/spezialkurse", "/de/store/category/courses/speciality/"],
  ["/de/store/category/courses/technical-diving-courses", "/de/store/category/courses/technical-diving-courses/"],
  ["/de/store/category/day-trips", "/de/store/category/day-trips/"],
  ["/de/store/category/Day-trips", "/de/store/category/day-trips/"],
  ["/de/suchen-und-bergen-beim-tauchen", "/de/posts/scuba-knowledge/about-search-recovery/"],
  ["/de/surface-marker-buoy-smb-warum-ist-sie-wichtig-und-was-bedeuten-die-farben", "/de/posts/scuba-knowledge/smb-guide/"],
  ["/de/sustainable-diving", "/de/posts/straight-talk/sustainable-diving/"],
  ["/de/tauchen-fuer-anfaenger-guide", "/de/posts/koh-chang-diving-travel-guides/beginner-guide/"],
  ["/de/tauchen-golf-von-thailand-vs-andamanensee", "/de/posts/koh-chang-diving-travel-guides/thailand-diving-comparison/"],
  ["/de/tauchen-mythen-und-wahrheit", "/de/posts/straight-talk/diving-myths/"],
  ["/de/tauchen-social-media", "/de/posts/straight-talk/diving-social-media/"],
  ["/de/terms-and-conditions", "/de/terms-and-conditions/"],
  ["/de/thailand-diving-comparison", "/de/posts/koh-chang-diving-travel-guides/thailand-diving-comparison/"],
  ["/de/tieftauchen-was-ist-das", "/de/posts/tips-and-tricks/deep-diving/"],
  ["/de/titan-drueckerfisch-koh-chang", "/de/posts/marine-life-koh-chang/marine-life-titan-triggerfish/"],
  ["/de/travel-guide", "/de/posts/koh-chang-diving-travel-guides/travel-guide/"],
  ["/de/unterwasserfotografie-tipps", "/de/posts/tips-and-tricks/about-underwater-photography/"],
  ["/de/walhaie-auf-koh-chang-eine-begegnung-der-besonderen-art", "/de/posts/marine-life-koh-chang/marine-life-whale-shark/"],
  ["/de/warum-der-advanced-open-water-diver", "/de/product/advanced/"],
  ["/de/warum-es-wichtig-ist-dein-tauchabenteuer-in-koh-chang-im-voraus-zu-buchen", "/de/posts/straight-talk/book-in-advance/"],
  ["/de/warum-ist-der-luftverbrauch-beim-tauchen-wichtig-chang-diving-center", "/de/posts/scuba-knowledge/gas-consumption/"],
  ["/de/warum-ist-der-luftverbrauch-beim-tauchen-wichtig", "/de/posts/scuba-knowledge/gas-consumption/"],
  ["/de/warum-ist-ein-sicherheitscheck-vor-dem-tauchen-auf-koh-chang-wichtig", "/de/posts/scuba-knowledge/safety-check/"],
  ["/de/was-ist-nitrox", "/de/posts/scuba-knowledge/nitrox-info/"],
  ["/de/weather", "/de/weather/"],
  ["/de/wetter-koh-chang", "/de/weather/"],
  ["/de/wie-ein-try-dive-bei-chang-diving-ablaeuft-schritt-fuer-schritt-2025-koh-chang", "/de/posts/diving-how-to-guides-koh-chang/how-to-try-dive/"],
  ["/de/wracktauchen-koh-chang", "/de/posts/scuba-knowledge/wreck-diving-koh-chang/"],
  ["/de/wreck-diving-koh-chang", "/de/posts/scuba-knowledge/wreck-diving-koh-chang/"],
  ["/en", "/en/"],
  ["/en/about", "/en/about/"],
  ["/en/about/dive-schedule", "/en/about/"],
  ["/en/about/refund-policy", "/en/about/"],
  ["/en/about/the-dive-process", "/en/about/"],
  ["/en/about-search-recovery", "/en/posts/scuba-knowledge/about-search-recovery/"],
  ["/en/about-underwater-photography", "/en/posts/tips-and-tricks/about-underwater-photography/"],
  ["/en/about-us", "/en/about/"],
  ["/en/contact", "/en/contact/"],
  ["/en/dive-professional-training", "/en/posts/straight-talk/dive-professional-training/"],
  ["/en/dive-sites", "/en/dive-sites/"],
  ["/en/dive-sites/blueberry-hill", "/en/dive-sites/blueberry-hill/"],
  ["/en/dive-sites/dive-site-map-koh-chang", "/en/dive-sites/dive-site-map-koh-chang/"],
  ["/en/dive-sites/hin-luk-bat", "/en/dive-sites/hin-luk-bat/"],
  ["/en/dive-sites/hin-pray-nam", "/en/dive-sites/hin-pray-nam/"],
  ["/en/dive-sites/hin-raab-north", "/en/dive-sites/hin-raab-north/"],
  ["/en/dive-sites/hin-raab-south", "/en/dive-sites/hin-raab-south/"],
  ["/en/dive-sites/hin-rua-tek", "/en/dive-sites/hin-rua-tek/"],
  ["/en/dive-sites/hin-sam-sao", "/en/dive-sites/hin-sam-sao/"],
  ["/en/dive-sites/htms-chang-wreck", "/en/dive-sites/htms-chang-wreck/"],
  ["/en/dive-sites/koh-rang-pinnacle", "/en/dive-sites/koh-rang-pinnacle/"],
  ["/en/dive-sites/koho-maru-5", "/en/dive-sites/koho-maru-5/"],
  ["/en/dive-sites/phutthayotfa-chulalok-wreck-koh-chang", "/en/dive-sites/phutthayotfa-chulalok-wreck-koh-chang/"],
  ["/en/dive-sites/secret-reef", "/en/dive-sites/secret-reef/"],
  ["/en/dive-sites/t11-wreck", "/en/dive-sites/t11-wreck/"],
  ["/en/diving-myths", "/en/posts/straight-talk/diving-myths/"],
  ["/en/diving-social-media", "/en/posts/straight-talk/diving-social-media/"],
  ["/en/emergency-plan", "/en/posts/straight-talk/emergency-plan/"],
  ["/en/faqs", "/en/faqs/"],
  ["/en/faqs/faq-booking-payment-scuba-koh-chang", "/en/faqs/faq-booking-payment-scuba-koh-chang/"],
  ["/en/faqs/faq-dive-courses-koh-chang", "/en/faqs/faq-dive-courses-koh-chang/"],
  ["/en/faqs/faq-diving-health-safety-thailand", "/en/faqs/faq-diving-health-safety-thailand/"],
  ["/en/faqs/faq-diving-koh-chang", "/en/faqs/faq-diving-koh-chang/"],
  ["/en/faqs/faq-equipment-logistics-koh-chang", "/en/faqs/faq-equipment-logistics-koh-chang/"],
  ["/en/faqs/faq-general-questions-koh-chang", "/en/faqs/faq-general-questions-koh-chang/"],
  ["/en/faqs/faq-try-dive-fun-dives-koh-chang", "/en/faqs/faq-try-dive-fun-dives-koh-chang/"],
  ["/en/faqs/getting-here-accommodation-frequently-asked-questions", "/en/faqs/faq-getting-here-accommodation/"],
  ["/en/gas-consumption", "/en/posts/scuba-knowledge/gas-consumption/"],
  ["/en/getting-to-koh-chang", "/en/faqs/faq-getting-here-accommodation/"],
  ["/en/how-to-advanced-course", "/en/posts/diving-how-to-guides-koh-chang/how-to-open-advanced/"],
  ["/en/how-to-fun-dives", "/en/posts/diving-how-to-guides-koh-chang/how-to-fun-dives/"],
  ["/en/how-to-open-advanced", "/en/posts/diving-how-to-guides-koh-chang/how-to-open-advanced/"],
  ["/en/how-to-open-water-course", "/en/posts/diving-how-to-guides-koh-chang/how-to-open-water-course/"],
  ["/en/how-to-scuba-review", "/en/posts/diving-how-to-guides-koh-chang/how-to-scuba-review/"],
  ["/en/how-to-specialty-courses", "/en/posts/diving-how-to-guides-koh-chang/how-to-specialty-courses/"],
  ["/en/how-to-try-dive", "/en/posts/diving-how-to-guides-koh-chang/how-to-try-dive/"],
  ["/en/life-as-a-diver", "/en/posts/straight-talk/dive-professional-training/"],
  ["/en/marine-life-barracuda", "/en/posts/marine-life-koh-chang/marine-life-barracuda/"],
  ["/en/marine-life-batfish", "/en/posts/marine-life-koh-chang/marine-life-batfish/"],
  ["/en/marine-life-blacktip-reef-shark", "/en/posts/marine-life-koh-chang/marine-life-blacktip-reef-shark/"],
  ["/en/marine-life-green-sea-turtle", "/en/posts/marine-life-koh-chang/marine-life-green-sea-turtle/"],
  ["/en/marine-life-nudibranch", "/en/posts/marine-life-koh-chang/marine-life-nudibranch/"],
  ["/en/marine-life-titan-triggerfish", "/en/posts/marine-life-koh-chang/marine-life-titan-triggerfish/"],
  ["/en/marine-life-whale-shark", "/en/posts/marine-life-koh-chang/marine-life-whale-shark/"],
  ["/en/marine-life", "/en/posts/marine-life-koh-chang/"],
  ["/en/nitrox-info", "/en/posts/scuba-knowledge/nitrox-info/"],
  ["/en/ocean-climate", "/en/posts/straight-talk/ocean-climate/"],
  ["/en/padi-vs-sdi-tdi", "/en/posts/straight-talk/padi-vs-sdi-tdi/"],
  ["/en/posts", "/en/posts/"],
  ["/en/posts/diving-how-to-guides-koh-chang", "/en/posts/diving-how-to-guides-koh-chang/"],
  ["/en/posts/diving-how-to-guides-koh-chang/how-to-advanced-course", "/en/posts/diving-how-to-guides-koh-chang/how-to-advanced-course/"],
  ["/en/posts/diving-how-to-guides-koh-chang/how-to-master-scuba-diver", "/en/posts/diving-how-to-guides-koh-chang/how-to-master-scuba-diver/"],
  ["/en/posts/diving-how-to-guides-koh-chang/how-to-open-water-course", "/en/posts/diving-how-to-guides-koh-chang/how-to-open-water-course/"],
  ["/en/posts/diving-how-to-guides-koh-chang/how-to-rescue-diver", "/en/posts/diving-how-to-guides-koh-chang/how-to-rescue-diver/"],
  ["/en/posts/koh-chang-diving-travel-guides", "/en/posts/koh-chang-diving-travel-guides/"],
  ["/en/posts/koh-chang-diving-travel-guides/beginner-guide", "/en/posts/koh-chang-diving-travel-guides/beginner-guide/"],
  ["/en/posts/marine-life-koh-chang", "/en/posts/marine-life-koh-chang/marine-life/"],
  ["/en/posts/marine-life-koh-chang/marine-life-blacktip-reef-shark", "/en/posts/marine-life-koh-chang/marine-life-blacktip-reef-shark/"],
  ["/en/posts/marine-life-koh-chang/marine-life-nudibranch", "/en/posts/marine-life-koh-chang/marine-life-nudibranch/"],
  ["/en/posts/marine-life-koh-chang/marine-life-titan-triggerfish", "/en/posts/marine-life-koh-chang/marine-life-titan-triggerfish/"],
  ["/en/posts/marine-life-koh-chang/marine-life-whale-shark", "/en/posts/marine-life-koh-chang/marine-life-whale-shark/"],
  ["/en/posts/scuba-knowledge", "/en/posts/scuba-knowledge/"],
  ["/en/posts/scuba-knowledge/about-search-recovery", "/en/posts/scuba-knowledge/about-search-recovery/"],
  ["/en/posts/scuba-knowledge/best-dive-computers", "/en/posts/scuba-knowledge/best-dive-computers/"],
  ["/en/posts/scuba-knowledge/smb-guide", "/en/posts/scuba-knowledge/smb-guide/"],
  ["/en/posts/straight-talk", "/en/posts/straight-talk/"],
  ["/en/posts/straight-talk/padi-vs-sdi-tdi", "/en/posts/straight-talk/padi-vs-sdi-tdi/"],
  ["/en/posts/tips-and-tricks", "/en/posts/tips-and-tricks/"],
  ["/en/prices", "/en/prices/"],
  ["/en/privacy-policy", "/en/privacy-policy/"],
  ["/en/product/advanced", "/en/product/advanced/"],
  ["/en/product/advanced-nitrox", "/en/product/advanced-nitrox/"],
  ["/en/product/advanced-wreck", "/en/product/advanced-wreck/"],
  ["/en/product/apeks-backplate", "/en/store/category/equipment/"],
  ["/en/product/apeks-black-ice", "/en/store/category/equipment/"],
  ["/en/product/apeks-bungee-connector-kit", "/en/store/category/equipment/"],
  ["/en/product/apeks-dry100l", "/en/store/category/equipment/"],
  ["/en/product/apeks-dry75-backpack", "/en/store/category/equipment/"],
  ["/en/product/apeks-dry75", "/en/store/category/equipment/"],
  ["/en/product/apeks-line-markers", "/en/store/category/equipment/"],
  ["/en/product/apeks-mtx-r-octopus", "/en/store/category/equipment/"],
  ["/en/product/apeks-mtx-r-regulator-set", "/en/store/category/equipment/"],
  ["/en/product/apeks-mtx-r", "/en/store/category/equipment/"],
  ["/en/product/apeks-mtx-rc-octopus", "/en/store/category/equipment/"],
  ["/en/product/apeks-mtx-rc", "/en/store/category/equipment/"],
  ["/en/product/apeks-regulator-service", "/en/store/category/equipment/"],
  ["/en/product/apeks-rk3-fins", "/en/store/category/equipment/"],
  ["/en/product/apeks-sidemount-harness", "/en/store/category/equipment/"],
  ["/en/product/apeks-spools-lifeline", "/en/store/category/equipment/"],
  ["/en/product/apeks-surface-marker-buoy", "/en/store/category/equipment/"],
  ["/en/product/apeks-tech-shorts", "/en/store/category/equipment/"],
  ["/en/product/apeks-tek3-regulator", "/en/store/category/equipment/"],
  ["/en/product/apeks-vx1-mask", "/en/store/category/equipment/"],
  ["/en/product/apeks-wsx-sidemount-harness", "/en/store/category/equipment/"],
  ["/en/product/apeks-wtx-deluxe-harness", "/en/store/category/equipment/"],
  ["/en/product/apeks-wtx-ultralight-travel-plate", "/en/store/category/equipment/"],
  ["/en/product/apeks-wtxd-double-wing-set", "/en/store/category/equipment/"],
  ["/en/product/apeks-wtxd-single-wing", "/en/store/category/equipment/"],
  ["/en/product/apeks-xl-4-regulator-set", "/en/store/category/equipment/"],
  ["/en/product/apeks-xl-4-set", "/en/store/category/equipment/"],
  ["/en/product/apeks-xl4-nitrox", "/en/store/category/equipment/"],
  ["/en/product/apeks-xl4-octopus", "/en/store/category/equipment/"],
  ["/en/product/apeks-xl4-regulator", "/en/store/category/equipment/"],
  ["/en/product/apeks-xtx-50-40regulator-set", "/en/store/category/equipment/"],
  ["/en/product/apeks-xtx40-nitrox-regulator", "/en/store/category/equipment/"],
  ["/en/product/apeks-xtx40-octopus", "/en/store/category/equipment/"],
  ["/en/product/apeks-xtx50-sidemount-set", "/en/store/category/equipment/"],
  ["/en/product/apeks-xtx50", "/en/store/category/equipment/"],
  ["/en/product/deco-procedures", "/en/product/deco-procedures/"],
  ["/en/product/deep-blue-dry-bags", "/en/store/category/equipment/"],
  ["/en/product/deep-blue-speed3-snorkel-fin", "/en/store/category/equipment/"],
  ["/en/product/deep-blue-xtreme-mask-set", "/en/store/category/equipment/"],
  ["/en/product/deep-blue-xtreme-mask", "/en/store/category/equipment/"],
  ["/en/product/deep-diver", "/en/product/deep-diver/"],
  ["/en/product/deep-wreck-nitrox", "/en/product/nitrox-diver/"],
  ["/en/product/divemaster", "/en/product/divemaster/"],
  ["/en/product/efr-instructor", "/en/product/efr-instructor/"],
  ["/en/product/emergency-first-response-instructor", "/en/product/efr-instructor/"],
  ["/en/product/first-aid", "/en/product/first-aid/"],
  ["/en/product/fun-dives", "/en/product/fun-dives/"],
  ["/en/product/hybrid-cargo-shorts", "/en/store/category/equipment/"],
  ["/en/product/hydros-pro-bcd", "/en/store/category/equipment/"],
  ["/en/product/instructor-crossover", "/en/product/instructor-crossover/"],
  ["/en/product/insurance", "/en/product/insurance/"],
  ["/en/product/intro-to-tech", "/en/product/intro-to-tech/"],
  ["/en/product/master-scuba-diver", "/en/product/master-scuba-diver/"],
  ["/en/product/navigation", "/en/product/navigation/"],
  ["/en/product/night", "/en/product/night/"],
  ["/en/product/nitrox-diver", "/en/product/nitrox-diver/"],
  ["/en/product/open-advanced-package", "/en/product/open-advanced-package/"],
  ["/en/product/open-to-divemaster", "/en/product/open-to-divemaster/"],
  ["/en/product/open-water-diver", "/en/product/open-water-diver/"],
  ["/en/product/open-water-diver-referral-course", "/en/product/open-water-diver/"],
  ["/en/product/open-water-scuba-instructor", "/en/product/sdi-idc/"],
  ["/en/product/rent-a-gopro-hero-7-black", "/en/product/rent-gopro/"],
  ["/en/product/rent-gopro", "/en/product/rent-gopro/"],
  ["/en/product/rescue-diver", "/en/product/rescue-diver/"],
  ["/en/product/s-tek-donut-wing", "/en/store/category/equipment/"],
  ["/en/product/scuba-review", "/en/product/scuba-review/"],
  ["/en/product/scubapro_r195_octopus", "/en/store/category/equipment/"],
  ["/en/product/scubapro-backplate", "/en/store/category/equipment/"],
  ["/en/product/scubapro-mash-bag", "/en/store/category/equipment/"],
  ["/en/product/scubapro-mk-25-evo-s600-set", "/en/store/category/equipment/"],
  ["/en/product/scubapro-mk21-c370-set", "/en/store/category/equipment/"],
  ["/en/product/scubapro-mk21-c370", "/en/store/category/equipment/"],
  ["/en/product/scubapro-mk25-evo-s600", "/en/store/category/equipment/"],
  ["/en/product/scubapro-single-tank-adapter-sta", "/en/store/category/equipment/"],
  ["/en/product/scubapro-solo-mask", "/en/store/category/equipment/"],
  ["/en/product/scubapro-t-one-bcd", "/en/store/category/equipment/"],
  ["/en/product/scubapro-x-tek-sidemount", "/en/store/category/equipment/"],
  ["/en/product/scubapro-x-tek-wing-set", "/en/store/category/equipment/"],
  ["/en/product/sdi-idc", "/en/product/sdi-idc/"],
  ["/en/product/sdi-ie", "/en/product/sdi-ie/"],
  ["/en/product/search-recovery", "/en/product/search-recovery/"],
  ["/en/product/sidemount", "/en/product/sidemount/"],
  ["/en/product/snorkeling", "/en/product/snorkeling/"],
  ["/en/product/solo-diver", "/en/product/solo-diver/"],
  ["/en/product/suunto-d4i-novo", "/en/store/category/equipment/"],
  ["/en/product/suunto-d5", "/en/store/category/equipment/"],
  ["/en/product/suunto-eon-core", "/en/store/category/equipment/"],
  ["/en/product/suunto-zoop-novo", "/en/store/category/equipment/"],
  ["/en/product/tech-package", "/en/product/tech-package/"],
  ["/en/product/try-dive", "/en/product/try-dive/"],
  ["/en/product/wreck-diver", "/en/product/wreck-diver/"],
  ["/en/product/x-tek-pure-tek-harness", "/en/store/category/equipment/"],
  ["/en/reel-guideline", "/en/posts/tips-and-tricks/reel-guideline/"],
  ["/en/refund-policy", "/en/refund-policy/"],
  ["/en/smb-guide", "/en/posts/scuba-knowledge/smb-guide/"],
  ["/en/store", "/en/store/"],
  ["/en/store", "/en/store/"],
  ["/en/store/category", "/en/store/category/"],
  ["/en/store/category/courses", "/en/store/category/courses/"],
  ["/en/store/category/courses/advanced-courses", "/en/store/category/courses/advanced-courses/"],
  ["/en/store/category/courses/beginner-courses", "/en/store/category/courses/beginner-courses/"],
  ["/en/store/category/courses/professional-courses", "/en/store/category/courses/professional-courses/"],
  ["/en/store/category/courses/speciality", "/en/store/category/courses/speciality/"],
  ["/en/store/category/courses/technical-diving-courses", "/en/store/category/courses/technical-diving-courses/"],
  ["/en/store/category/courses/technical-diving-courses/%E2%80%9E", "/en/store/category/courses/technical-diving-courses/"],
  ["/en/store/category/day-trips", "/en/store/category/day-trips/"],
  ["/en/store/category/equipment", "/en/store/category/equipment/"],
  ["/en/store/category/packages", "/en/store/category/courses/"],
  ["/en/store/courses/advanced-open-water-diver", "/en/product/advanced/"],
  ["/en/store/courses/divemaster", "/en/product/divemaster/"],
  ["/en/store/courses/open-water-diver", "/en/product/open-water-diver/"],
  ["/en/store/courses/rescue-diver", "/en/product/rescue-diver/"],
  ["/en/store/courses/sdi-instructor-development-course-idc", "/en/product/sdi-idc/"],
  ["/en/store/day-trips/discover-scuba-diving", "/en/product/try-dive/"],
  ["/en/store/day-trips/fun-dives", "/en/product/fun-dives/"],
  ["/en/store/day-trips/scuba-review", "/en/product/scuba-review/"],
  ["/en/store/day-trips/snorkeling", "/en/product/snorkeling/"],
  ["/en/store/packages/deep-wreck-nitrox", "/en/product/nitrox-diver/"],
  ["/en/store/packages/open-water-advanced-open-water-diver", "/en/product/open-advanced-package/"],
  ["/en/store/packages/open-water-diver-to-divemaster", "/en/product/open-to-divemaster/"],
  ["/en/store/packages/tdi-technical-diver-training", "/en/product/tech-package/"],
  ["/en/sustainable-diving", "/en/posts/straight-talk/sustainable-diving/"],
  ["/en/terms-and-conditions", "/en/terms-and-conditions/"],
  ["/en/thailand-diving-comparison", "/en/posts/koh-chang-diving-travel-guides/thailand-diving-comparison/"],
  ["/en/travel-guide", "/en/posts/koh-chang-diving-travel-guides/travel-guide/"],
  ["/en/weather", "/en/weather/"],
  ["/en/which-course", "/en/posts/tips-and-tricks/which-course/"],
  ["/en/wreck-diving-koh-chang", "/en/posts/scuba-knowledge/wreck-diving-koh-chang/"],
  ["/th", "/th/"],
  ["/th/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3-try-dive-%E0%B8%81%E0%B8%B1%E0%B8%9A-chang-diving-%E0%B8%82%E0%B8%B1%E0%B9%89%E0%B8%99%E0%B8%95%E0%B8%AD%E0%B8%99%E0%B8%87", "/th/posts/diving-how-to-guides-koh-chang/how-to-try-dive/"],
  ["/th/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%97%E0%B8%B3%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B8%82%E0%B8%AD%E0%B8%87-apeks-dst4", "/th/store/category/equipment/"],
  ["/th/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%80%E0%B8%94%E0%B8%B4%E0%B8%99%E0%B8%97%E0%B8%B2%E0%B8%87%E0%B9%84%E0%B8%9B%E0%B9%80%E0%B8%81%E0%B8%B2%E0%B8%B0%E0%B8%8A%E0%B9%89%E0%B8%B2%E0%B8%87", "/th/faqs/faq-getting-here-accommodation/"],
  ["/th/%E0%B8%89%E0%B8%A5%E0%B8%B2%E0%B8%A1%E0%B8%A7%E0%B8%B2%E0%B8%AC%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B9%80%E0%B8%81%E0%B8%B2%E0%B8%B0%E0%B8%8A%E0%B9%89%E0%B8%B2%E0%B8%87-%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%AA", "/th/posts/marine-life-koh-chang/marine-life-whale-shark/"],
  ["/th/%E0%B8%89%E0%B8%A5%E0%B8%B2%E0%B8%A1%E0%B8%A7%E0%B8%B2%E0%B8%AC%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B9%80%E0%B8%81%E0%B8%B2%E0%B8%B0%E0%B8%8A%E0%B9%89%E0%B8%B2%E0%B8%87-%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%AA", "/th/posts/marine-life-koh-chang/marine-life-whale-shark/"],
  ["/th/%E0%B8%95%E0%B8%B4%E0%B8%94%E0%B8%95%E0%B9%88%E0%B8%AD", "/th/contact/"],
  ["/th/%E0%B8%95%E0%B8%B4%E0%B8%94%E0%B8%95%E0%B9%88%E0%B8%AD%E0%B9%80%E0%B8%A3%E0%B8%B2", "/th/contact/"],
  ["/th/%E0%B8%9B%E0%B8%A5%E0%B8%B2%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%9B%E0%B8%B0%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%B1%E0%B8%87-%E0%B9%80%E0%B8%81%E0%B8%B2%E0%B8%B0%E0%B8%8A%E0%B9%89%E0%B8%B2%E0%B8%87-%E0%B8%88", "/th/posts/marine-life-koh-chang/"],
  ["/th/%E0%B8%9B%E0%B8%A5%E0%B8%B2%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%9B%E0%B8%B0%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%B1%E0%B8%87-%E0%B9%80%E0%B8%81%E0%B8%B2%E0%B8%B0%E0%B8%8A%E0%B9%89%E0%B8%B2%E0%B8%87-%E0%B8%88", "/th/posts/marine-life-koh-chang/"],
  ["/th/%E0%B8%9B%E0%B8%A5%E0%B8%B2%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%9B%E0%B8%B0%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%B1%E0%B8%87-%E0%B9%80%E0%B8%81%E0%B8%B2%E0%B8%B0%E0%B8%8A%E0%B9%89%E0%B8%B2%E0%B8%87-%E0%B8%95", "/th/posts/marine-life-koh-chang/"],
  ["/th/%E0%B8%9B%E0%B8%A5%E0%B8%B2%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%9B%E0%B8%B0%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%B1%E0%B8%87-%E0%B9%80%E0%B8%81%E0%B8%B2%E0%B8%B0%E0%B8%8A%E0%B9%89%E0%B8%B2%E0%B8%87-%E0%B8%95", "/th/posts/marine-life-koh-chang/"],
  ["/th/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3-open-water-%E0%B8%81%E0%B8%B1%E0%B8%9A-chang-diving-%E0%B8%84%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%AA", "/th/posts/diving-how-to-guides-koh-chang/how-to-open-water-course/"],
  ["/th/%E0%B9%80%E0%B8%AA%E0%B9%89%E0%B8%99%E0%B8%97%E0%B8%B2%E0%B8%87%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3", "/th/posts/straight-talk/dive-professional-training/"],
  ["/th/about", "/th/about/"],
  ["/th/about/dive-schedule", "/th/about/"],
  ["/th/about-search-recovery", "/th/posts/scuba-knowledge/about-search-recovery/"],
  ["/th/about-us", "/th/about/"],
  ["/th/apeks-dst4", "/th/store/category/equipment/"],
  ["/th/apeks-first-stage-operation-dst4", "/th/store/category/equipment/"],
  ["/th/apeks-xtx", "/th/store/category/equipment/"],
  ["/th/category/diving-how-to-guides-koh-chang", "/th/posts/diving-how-to-guides-koh-chang/"],
  ["/th/category/marine-life-koh-chang", "/th/posts/marine-life-koh-chang/"],
  ["/th/deep-diving", "/th/posts/tips-and-tricks/deep-diving/"],
  ["/th/dive-courses/advanced-open-water", "/th/product/advanced/"],
  ["/th/dive-logbook", "/th/posts/scuba-knowledge/dive-logbook/"],
  ["/th/dive-professional-training", "/th/posts/straight-talk/dive-professional-training/"],
  ["/th/dive-sites", "/th/dive-sites/"],
  ["/th/dive-sites/blueberry-hill", "/th/dive-sites/blueberry-hill/"],
  ["/th/dive-sites/dive-site-map-koh-chang", "/th/dive-sites/dive-site-map-koh-chang/"],
  ["/th/dive-sites/hin-kra-duang", "/th/dive-sites/"],
  ["/th/dive-sites/hin-luk-bat", "/th/dive-sites/hin-luk-bat/"],
  ["/th/dive-sites/hin-pray-nam", "/th/dive-sites/hin-pray-nam/"],
  ["/th/dive-sites/hin-raab-north", "/th/dive-sites/hin-raab-north/"],
  ["/th/dive-sites/hin-raab-south", "/th/dive-sites/hin-raab-south/"],
  ["/th/dive-sites/hin-rua-tek", "/th/dive-sites/hin-rua-tek/"],
  ["/th/dive-sites/hin-ruea-taek", "/th/dive-sites/hin-rua-tek/"],
  ["/th/dive-sites/hin-sam-sao", "/th/dive-sites/hin-sam-sao/"],
  ["/th/dive-sites/htms-chang-wreck", "/th/dive-sites/htms-chang-wreck/"],
  ["/th/dive-sites/koh-rang-pinnacle", "/th/dive-sites/koh-rang-pinnacle/"],
  ["/th/dive-sites/koho-maru-5", "/th/dive-sites/koho-maru-5/"],
  ["/th/dive-sites/phutthayotfa-chulalok-wreck-koh-chang", "/th/dive-sites/phutthayotfa-chulalok-wreck-koh-chang/"],
  ["/th/dive-sites/secret-reef", "/th/dive-sites/secret-reef/"],
  ["/th/dive-sites/t11-wreck", "/th/dive-sites/t11-wreck/"],
  ["/th/diving-activities", "/th/posts/tips-and-tricks/diving-activities/"],
  ["/th/diving-myths", "/th/posts/straight-talk/diving-myths/"],
  ["/th/diving-thailand-gulf-vs-andaman", "/th/posts/koh-chang-diving-travel-guides/thailand-diving-comparison/"],
  ["/th/emergency-plan", "/th/posts/straight-talk/emergency-plan/"],
  ["/th/faqs", "/th/faqs/"],
  ["/th/faqs/faq-booking-payment-scuba-koh-chang", "/th/faqs/faq-booking-payment-scuba-koh-chang/"],
  ["/th/faqs/faq-dive-courses-koh-chang", "/th/faqs/faq-dive-courses-koh-chang/"],
  ["/th/faqs/faq-diving-koh-chang", "/th/faqs/faq-diving-koh-chang/"],
  ["/th/faqs/faq-equipment-logistics-koh-chang", "/th/faqs/faq-equipment-logistics-koh-chang/"],
  ["/th/faqs/faq-general-questions-koh-chang", "/th/faqs/faq-general-questions-koh-chang/"],
  ["/th/faqs/faq-getting-here-accommodation", "/th/faqs/faq-getting-here-accommodation/"],
  ["/th/faqs/faq-try-dive-fun-dives-koh-chang", "/th/product/fun-dives/"],
  ["/th/faqs/getting-here-accommodation-frequently-asked-questions", "/th/faqs/faq-getting-here-accommodation/"],
  ["/th/gas-consumption", "/th/posts/scuba-knowledge/gas-consumption/"],
  ["/th/getting-to-koh-chang", "/th/faqs/faq-getting-here-accommodation/"],
  ["/th/green-sea-turtle-koh-chang", "/th/posts/marine-life-koh-chang/marine-life-green-sea-turtle/"],
  ["/th/how-to-fun-dives", "/th/product/fun-dives/"],
  ["/th/how-to-open-water-course", "/th/posts/diving-how-to-guides-koh-chang/how-to-open-water-course/"],
  ["/th/how-to-specialty-courses", "/th/posts/diving-how-to-guides-koh-chang/how-to-specialty-courses/"],
  ["/th/how-to-try-dive", "/th/posts/diving-how-to-guides-koh-chang/how-to-try-dive/"],
  ["/th/index.html", "/th/"],
  ["/th/koh-chang-travel-guide", "/th/posts/koh-chang-diving-travel-guides/travel-guide/"],
  ["/th/life-as-a-diver", "/th/posts/straight-talk/dive-professional-training/"],
  ["/th/marine-life-barracuda", "/th/posts/marine-life-koh-chang/marine-life-barracuda/"],
  ["/th/marine-life-batfish", "/th/posts/marine-life-koh-chang/marine-life-batfish/"],
  ["/th/marine-life-blacktip-reef-shark", "/th/posts/marine-life-koh-chang/marine-life-blacktip-reef-shark/"],
  ["/th/marine-life-titan-triggerfish", "/th/posts/marine-life-koh-chang/marine-life-titan-triggerfish/"],
  ["/th/marine-life-whale-shark", "/th/posts/marine-life-koh-chang/marine-life-whale-shark/"],
  ["/th/marine-life", "/th/posts/marine-life-koh-chang/"],
  ["/th/nitrox-info", "/th/posts/scuba-knowledge/nitrox-info/"],
  ["/th/nudibranchs-koh-chang", "/th/posts/marine-life-koh-chang/marine-life-nudibranch/"],
  ["/th/padi-vs-sdi-tdi", "/th/posts/straight-talk/padi-vs-sdi-tdi/"],
  ["/th/posts", "/th/posts/"],
  ["/th/posts/diving-how-to-guides-koh-chang", "/th/posts/diving-how-to-guides-koh-chang/"],
  ["/th/posts/diving-how-to-guides-koh-chang/how-to-advanced-course", "/th/posts/diving-how-to-guides-koh-chang/how-to-advanced-course/"],
  ["/th/posts/diving-how-to-guides-koh-chang/how-to-open-advanced", "/th/posts/diving-how-to-guides-koh-chang/how-to-open-advanced/"],
  ["/th/posts/diving-how-to-guides-koh-chang/how-to-rescue-diver", "/th/posts/diving-how-to-guides-koh-chang/how-to-rescue-diver/"],
  ["/th/posts/diving-how-to-guides-koh-chang/how-to-specialty-courses", "/th/posts/diving-how-to-guides-koh-chang/how-to-specialty-courses/"],
  ["/th/posts/koh-chang-diving-travel-guides", "/th/posts/koh-chang-diving-travel-guides/"],
  ["/th/posts/marine-life-koh-chang", "/th/posts/marine-life-koh-chang/"],
  ["/th/posts/marine-life-koh-chang/marine-life", "/th/posts/marine-life-koh-chang/marine-life/"],
  ["/th/posts/marine-life-koh-chang/marine-life-batfish", "/th/posts/marine-life-koh-chang/marine-life-batfish/"],
  ["/th/posts/scuba-knowledge", "/th/posts/scuba-knowledge/"],
  ["/th/posts/scuba-knowledge/about-search-recovery", "/th/posts/scuba-knowledge/about-search-recovery/"],
  ["/th/posts/straight-talk/book-in-advance", "/th/posts/straight-talk/book-in-advance/"],
  ["/th/posts/straight-talk/diving-social-media", "/th/posts/straight-talk/diving-social-media/"],
  ["/th/posts/straight-talk/emergency-plan", "/th/posts/straight-talk/emergency-plan/"],
  ["/th/posts/straight-talk/padi-vs-sdi-tdi", "/th/posts/straight-talk/padi-vs-sdi-tdi/"],
  ["/th/posts/tips-and-tricks", "/th/posts/tips-and-tricks/"],
  ["/th/posts/tips-and-tricks/reel-guideline", "/th/posts/tips-and-tricks/reel-guideline/"],
  ["/th/prices", "/th/prices/"],
  ["/th/privacy-policy", "/th/privacy-policy/"],
  ["/th/product/%E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B9%80%E0%B8%9B%E0%B9%8B%E0%B8%B2%E0%B8%95%E0%B8%B2%E0%B8%82%E0%B8%B2%E0%B8%A2", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B9%80%E0%B8%9B%E0%B9%8B%E0%B8%B2%E0%B8%AA%E0%B8%B0%E0%B8%9E%E0%B8%B2%E0%B8%A2-apeks-dry75", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%81%E0%B8%B2%E0%B8%87%E0%B9%80%E0%B8%81%E0%B8%87%E0%B8%82%E0%B8%B2%E0%B8%AA%E0%B8%B1%E0%B8%99-hybrid-cargo-1%E0%B8%A1%E0%B8%A1", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%AA%E0%B8%AD%E0%B8%9A%E0%B8%84%E0%B8%A3%E0%B8%B9%E0%B8%9C%E0%B8%B9%E0%B9%89%E0%B8%AA%E0%B8%AD%E0%B8%99%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%82%E0%B8%AD", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%AA%E0%B8%AD%E0%B8%9A%E0%B8%84%E0%B8%A3%E0%B8%B9%E0%B8%9C%E0%B8%B9%E0%B9%89%E0%B8%AA%E0%B8%AD%E0%B8%99%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%82%E0%B8%AD", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%84%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%AA%E0%B8%84%E0%B8%A3%E0%B8%B9%E0%B8%AA%E0%B8%AD%E0%B8%99%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%A5%E0%B8%B6%E0%B8%81sd", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%84%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%AA%E0%B8%84%E0%B8%A3%E0%B8%B9%E0%B8%AA%E0%B8%AD%E0%B8%99%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%A5%E0%B8%B6%E0%B8%81sd", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%84%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%AA%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%9C%E0%B8%B9%E0%B9%89%E0%B8%99%E0%B8%B3-%E0%B9%84%E0%B8%81%E0%B8%84%E0%B9%8C", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%84%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%AA%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%9C%E0%B8%B9%E0%B9%89%E0%B8%99%E0%B8%B3-%E0%B9%84%E0%B8%81%E0%B8%84%E0%B9%8C", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%8A%E0%B8%B8%E0%B8%94%E0%B9%80%E0%B8%A3%E0%B8%81%E0%B8%81%E0%B8%B9%E0%B9%80%E0%B8%A5%E0%B9%80%E0%B8%95%E0%B8%AD%E0%B8%A3%E0%B9%8C-apeks-mtx-r-sidemount", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%8A%E0%B8%B8%E0%B8%94%E0%B9%80%E0%B8%A3%E0%B8%81%E0%B8%81%E0%B8%B9%E0%B9%80%E0%B8%A5%E0%B9%80%E0%B8%95%E0%B8%AD%E0%B8%A3%E0%B9%8C-apeks-mtx-rc", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%8A%E0%B8%B8%E0%B8%94%E0%B9%80%E0%B8%A3%E0%B8%81%E0%B8%81%E0%B8%B9%E0%B9%80%E0%B8%A5%E0%B9%80%E0%B8%95%E0%B8%AD%E0%B8%A3%E0%B9%8C-apeks-xl4-2", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%8A%E0%B8%B8%E0%B8%94%E0%B9%80%E0%B8%A3%E0%B8%81%E0%B8%81%E0%B8%B9%E0%B9%80%E0%B8%A5%E0%B9%80%E0%B8%95%E0%B8%AD%E0%B8%A3%E0%B9%8C-apeks-xtx-50-40", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%8A%E0%B8%B8%E0%B8%94%E0%B9%80%E0%B8%A3%E0%B8%81%E0%B8%81%E0%B8%B9%E0%B9%80%E0%B8%A5%E0%B9%80%E0%B8%95%E0%B8%AD%E0%B8%A3%E0%B9%8C-apeks-xtx50-sidemount", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%95%E0%B8%B7%E0%B9%89%E0%B8%99", "/th/product/snorkeling/"],
  ["/th/product/%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%95%E0%B8%B7%E0%B9%89%E0%B8%99%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B9%80%E0%B8%81%E0%B8%B2%E0%B8%B0%E0%B8%8A%E0%B9%89%E0%B8%B2%E0%B8%87-%E0%B8%AA", "/th/product/snorkeling/"],
  ["/th/product/%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%AA%E0%B8%84%E0%B8%B9%E0%B8%9A%E0%B9%89%E0%B8%B2-%E0%B8%AA%E0%B8%B3%E0%B8%AB%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%9C%E0%B8%B9%E0%B9%89%E0%B9%84%E0%B8%A1", "/th/product/fun-dives/"],
  ["/th/product/%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%AA%E0%B8%84%E0%B8%B9%E0%B8%9A%E0%B9%89%E0%B8%B2-%E0%B8%AA%E0%B8%B3%E0%B8%AB%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%9C%E0%B8%B9%E0%B9%89%E0%B9%84%E0%B8%A1", "/th/product/fun-dives/"],
  ["/th/product/%E0%B8%95%E0%B8%B5%E0%B8%99%E0%B8%81%E0%B8%9A-apeks-rk3", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%95%E0%B8%B5%E0%B8%99%E0%B8%81%E0%B8%9A-deep-blue-speed3-snorkel", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%95%E0%B8%B5%E0%B8%99%E0%B8%81%E0%B8%9A-go-travel", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%96%E0%B8%B8%E0%B8%87%E0%B8%A5%E0%B8%A1-scubapro-x-tek", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%96%E0%B8%B8%E0%B8%87%E0%B8%A5%E0%B8%A1-wtx-d-double-donut-wing", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%96%E0%B8%B8%E0%B8%87%E0%B8%A5%E0%B8%A1-x-tek-40-donut-wing", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%97%E0%B8%A3%E0%B8%B4%E0%B8%9B%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%A5%E0%B8%B6%E0%B8%81%E0%B8%AA%E0%B8%84%E0%B8%B9%E0%B8%9A%E0%B9%89%E0%B8%B2-%E0%B8%9F%E0%B8%B1%E0%B8%99%E0%B9%84", "/th/product/fun-dives/"],
  ["/th/product/%E0%B8%97%E0%B8%A3%E0%B8%B4%E0%B8%9B%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%A5%E0%B8%B6%E0%B8%81%E0%B8%AA%E0%B8%84%E0%B8%B9%E0%B8%9A%E0%B9%89%E0%B8%B2-%E0%B8%9F%E0%B8%B1%E0%B8%99%E0%B9%84", "/th/product/fun-dives/"],
  ["/th/product/%E0%B8%97%E0%B8%B8%E0%B9%88%E0%B8%99%E0%B8%97%E0%B8%B3%E0%B9%80%E0%B8%84%E0%B8%A3%E0%B8%B7%E0%B9%88%E0%B8%AD%E0%B8%87%E0%B8%AB%E0%B8%A1%E0%B8%B2%E0%B8%A2-apeks-smb", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%9A%E0%B8%A3%E0%B8%B4%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%8B%E0%B9%88%E0%B8%AD%E0%B8%A1-%E0%B8%9A%E0%B8%B3%E0%B8%A3%E0%B8%B8%E0%B8%87-apeks-regulator", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%9A%E0%B8%B5%E0%B8%8B%E0%B8%B5%E0%B8%94%E0%B8%B5-apeks-black-ice", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%9A%E0%B8%B5%E0%B8%8B%E0%B8%B5%E0%B8%94%E0%B8%B5-apeks-wsx-sidemount-harness", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%9A%E0%B8%B5%E0%B8%8B%E0%B8%B5%E0%B8%94%E0%B8%B5-hydros-pro", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%9A%E0%B8%B5%E0%B8%8B%E0%B8%B5%E0%B8%94%E0%B8%B5-scubapro-t-one", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%9A%E0%B8%B5%E0%B8%8B%E0%B8%B5%E0%B8%94%E0%B8%B5-scubapro-x-tek-40", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%81%E0%B8%B1%E0%B8%99%E0%B8%A0%E0%B8%B1%E0%B8%A2%E0%B8%AD%E0%B8%B8%E0%B8%9A%E0%B8%B1%E0%B8%95%E0%B8%B4%E0%B9%80%E0%B8%AB%E0%B8%95%E0%B8%B8%E0%B8%81%E0%B8%B2%E0%B8%A3", "/th/product/insurance/"],
  ["/th/product/%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%81%E0%B8%B1%E0%B8%99%E0%B8%A0%E0%B8%B1%E0%B8%A2%E0%B8%AD%E0%B8%B8%E0%B8%9A%E0%B8%B1%E0%B8%95%E0%B8%B4%E0%B9%80%E0%B8%AB%E0%B8%95%E0%B8%B8%E0%B8%81%E0%B8%B2%E0%B8%A3", "/th/product/insurance/"],
  ["/th/product/%E0%B8%9F%E0%B8%B1%E0%B8%99%E0%B9%84%E0%B8%94%E0%B8%9F%E0%B9%8C", "/th/product/fun-dives/"],
  ["/th/product/%E0%B8%9F%E0%B8%B1%E0%B8%99%E0%B9%84%E0%B8%94%E0%B8%9F%E0%B9%8C%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B9%80%E0%B8%81%E0%B8%B2%E0%B8%B0%E0%B8%8A%E0%B9%89%E0%B8%B2%E0%B8%87", "/th/product/fun-dives/"],
  ["/th/product/%E0%B8%A3%E0%B8%AD%E0%B8%81%E0%B9%80%E0%B8%8A%E0%B8%B7%E0%B8%AD%E0%B8%81-apeks-spools-lifeline", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%AA%E0%B8%A1%E0%B8%B8%E0%B8%94%E0%B8%9A%E0%B8%B1%E0%B8%99%E0%B8%97%E0%B8%B6%E0%B8%81%E0%B9%83%E0%B8%95%E0%B9%89%E0%B8%99%E0%B9%89%E0%B8%B3-apeks-wetnotes", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%AB%E0%B8%99%E0%B9%89%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%81-apeks-vx1", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%AB%E0%B8%99%E0%B9%89%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%81-deep-blue-xtreme", "/th/store/category/equipment/"],
  ["/th/product/%E0%B8%AB%E0%B8%99%E0%B9%89%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%81-scubapro-solo", "/th/store/category/equipment/"],
  ["/th/product/%E0%B9%80%E0%B8%8A%E0%B9%88%E0%B8%B2-gopro-hero-7-black", "/th/product/rent-gopro/"],
  ["/th/product/%E0%B9%80%E0%B8%A3%E0%B8%81%E0%B8%81%E0%B8%B9%E0%B9%80%E0%B8%A5%E0%B9%80%E0%B8%95%E0%B8%AD%E0%B8%A3%E0%B9%8C-apeks-mtx-rc", "/th/store/category/equipment/"],
  ["/th/product/%E0%B9%80%E0%B8%A3%E0%B8%81%E0%B8%81%E0%B8%B9%E0%B9%80%E0%B8%A5%E0%B9%80%E0%B8%95%E0%B8%AD%E0%B8%A3%E0%B9%8C-apeks-tek3", "/th/store/category/equipment/"],
  ["/th/product/%E0%B9%80%E0%B8%A3%E0%B8%81%E0%B8%81%E0%B8%B9%E0%B9%80%E0%B8%A5%E0%B9%80%E0%B8%95%E0%B8%AD%E0%B8%A3%E0%B9%8C-apeks-xl4-2", "/th/store/category/equipment/"],
  ["/th/product/%E0%B9%80%E0%B8%A3%E0%B8%81%E0%B8%81%E0%B8%B9%E0%B9%80%E0%B8%A5%E0%B9%80%E0%B8%95%E0%B8%AD%E0%B8%A3%E0%B9%8C-apeks-xl4", "/th/store/category/equipment/"],
  ["/th/product/%E0%B9%80%E0%B8%A3%E0%B8%81%E0%B8%81%E0%B8%B9%E0%B9%80%E0%B8%A5%E0%B9%80%E0%B8%95%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%AA%E0%B8%B3%E0%B8%A3%E0%B8%AD%E0%B8%87-apeks-mtx-r-octopus", "/th/store/category/equipment/"],
  ["/th/product/%E0%B9%80%E0%B8%A3%E0%B8%81%E0%B8%81%E0%B8%B9%E0%B9%80%E0%B8%A5%E0%B9%80%E0%B8%95%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%AA%E0%B8%B3%E0%B8%A3%E0%B8%AD%E0%B8%87-apeks-xl4-octopus", "/th/store/category/equipment/"],
  ["/th/product/%E0%B9%80%E0%B8%A3%E0%B8%81%E0%B8%81%E0%B8%B9%E0%B9%80%E0%B8%A5%E0%B9%80%E0%B8%95%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%AA%E0%B8%B3%E0%B8%A3%E0%B8%AD%E0%B8%87-scubapro_r195_octopus", "/th/store/category/equipment/"],
  ["/th/product/advanced", "/th/product/advanced/"],
  ["/th/product/advanced-nitrox", "/th/product/advanced-nitrox/"],
  ["/th/product/advanced-wreck", "/th/product/advanced-wreck/"],
  ["/th/product/apeks-black-ice", "/th/store/category/equipment/"],
  ["/th/product/apeks-bungee-connector-kit", "/th/store/category/equipment/"],
  ["/th/product/apeks-dry100l", "/th/store/category/equipment/"],
  ["/th/product/apeks-dry75", "/th/store/category/equipment/"],
  ["/th/product/apeks-line-markers", "/th/store/category/equipment/"],
  ["/th/product/apeks-mtx-r-regulator-set", "/th/store/category/equipment/"],
  ["/th/product/apeks-mtx-r-sidemount-set", "/th/store/category/equipment/"],
  ["/th/product/apeks-mtx-r", "/th/store/category/equipment/"],
  ["/th/product/apeks-mtx-rc-regulator-set", "/th/store/category/equipment/"],
  ["/th/product/apeks-mtx-rc", "/th/store/category/equipment/"],
  ["/th/product/apeks-pressure-gauge", "/th/store/category/equipment/"],
  ["/th/product/apeks-rk3-fins", "/th/store/category/equipment/"],
  ["/th/product/apeks-sidemount-harness", "/th/store/category/equipment/"],
  ["/th/product/apeks-single-tank-adapter", "/th/store/category/equipment/"],
  ["/th/product/apeks-spools-lifeline", "/th/store/category/equipment/"],
  ["/th/product/apeks-surface-marker-buoy", "/th/store/category/equipment/"],
  ["/th/product/apeks-vx1-mask", "/th/store/category/equipment/"],
  ["/th/product/apeks-wetnotes", "/th/store/category/equipment/"],
  ["/th/product/apeks-wtx-deluxe-harness", "/th/store/category/equipment/"],
  ["/th/product/apeks-wtx-ultralight-travel-plate", "/th/store/category/equipment/"],
  ["/th/product/apeks-wtxd-double-wing-set", "/th/store/category/equipment/"],
  ["/th/product/apeks-wtxd-single-wing", "/th/store/category/equipment/"],
  ["/th/product/apeks-xl-4-regulator-set", "/th/store/category/equipment/"],
  ["/th/product/apeks-xl-4-set", "/th/store/category/equipment/"],
  ["/th/product/apeks-xl4", "/th/store/category/equipment/"],
  ["/th/product/apeks-xtx-50-40regulator-set", "/th/store/category/equipment/"],
  ["/th/product/apeks-xtx40-octopus", "/th/store/category/equipment/"],
  ["/th/product/apeks-xtx50-sidemount-set", "/th/store/category/equipment/"],
  ["/th/product/apeks-xtx50", "/th/store/category/equipment/"],
  ["/th/product/deco-procedures", "/th/product/deco-procedures/"],
  ["/th/product/deep-blue-speed3-snorkel-fin", "/th/store/category/equipment/"],
  ["/th/product/deep-blue-xtreme-mask-set", "/th/store/category/equipment/"],
  ["/th/product/deep-diver", "/th/product/deep-diver/"],
  ["/th/product/deep-wreck-nitrox", "/th/product/nitrox-diver/"],
  ["/th/product/divemaster", "/th/product/divemaster/"],
  ["/th/product/efr-instructor", "/th/product/efr-instructor/"],
  ["/th/product/first-aid", "/th/product/first-aid/"],
  ["/th/product/fun-dives", "/th/product/fun-dives/"],
  ["/th/product/go-sport-fin", "/th/store/category/equipment/"],
  ["/th/product/go-travel-fin", "/th/store/category/equipment/"],
  ["/th/product/gopro7", "/th/product/rent-gopro/"],
  ["/th/product/hydros-pro-bcd", "/th/store/category/equipment/"],
  ["/th/product/instructor-crossover", "/th/product/instructor-crossover/"],
  ["/th/product/insurance", "/th/product/insurance/"],
  ["/th/product/insurance/%E2%80%9E", "/th/product/insurance/"],
  ["/th/product/intro-to-tech", "/th/product/intro-to-tech/"],
  ["/th/product/master-scuba-diver", "/th/product/master-scuba-diver/"],
  ["/th/product/navigation", "/th/product/navigation/"],
  ["/th/product/night", "/th/product/night/"],
  ["/th/product/nitrox-diver", "/th/product/nitrox-diver/"],
  ["/th/product/open-advanced-package", "/th/product/open-advanced-package/"],
  ["/th/product/open-to-divemaster", "/th/product/open-to-divemaster/"],
  ["/th/product/open-water-diver", "/th/product/open-water-diver/"],
  ["/th/product/rent-gopro", "/th/product/rent-gopro/"],
  ["/th/product/rescue-diver", "/th/product/rescue-diver/"],
  ["/th/product/s-tek-donut-wing", "/th/store/category/equipment/"],
  ["/th/product/s-tek-pure-tek-harness", "/th/store/category/equipment/"],
  ["/th/product/scuba-review", "/th/product/scuba-review/"],
  ["/th/product/scubapro_r195_octopus", "/th/store/category/equipment/"],
  ["/th/product/scubapro-mash-bag", "/th/store/category/equipment/"],
  ["/th/product/scubapro-mk-25-evo-s600-set", "/th/store/category/equipment/"],
  ["/th/product/scubapro-mk25-evo-s600", "/th/store/category/equipment/"],
  ["/th/product/scubapro-pressure-gauge", "/th/store/category/equipment/"],
  ["/th/product/scubapro-solo-mask", "/th/store/category/equipment/"],
  ["/th/product/scubapro-t-one-bcd", "/th/store/category/equipment/"],
  ["/th/product/scubapro-x-tek-40", "/th/store/category/equipment/"],
  ["/th/product/scubapro-x-tek-sidemountt", "/th/store/category/equipment/"],
  ["/th/product/sdi-idc", "/th/product/sdi-idc/"],
  ["/th/product/sdi-ie", "/th/product/sdi-ie/"],
  ["/th/product/search-and-recovery-diver", "/th/product/search-recovery/"],
  ["/th/product/search-recovery", "/th/product/search-recovery/"],
  ["/th/product/sidemount", "/th/product/sidemount/"],
  ["/th/product/snorkeling", "/th/product/snorkeling/"],
  ["/th/product/solo-diver", "/th/product/solo-diver/"],
  ["/th/product/suunto-d4i-novo", "/th/store/category/equipment/"],
  ["/th/product/suunto-eon-core", "/th/store/category/equipment/"],
  ["/th/product/suunto-zoop-novo", "/th/store/category/equipment/"],
  ["/th/product/tech-package", "/th/product/tech-package/"],
  ["/th/product/try-dive", "/th/product/try-dive/"],
  ["/th/product/wreck-diver", "/th/product/wreck-diver/"],
  ["/th/product/wtx-d-double-donut-wing", "/th/store/category/equipment/"],
  ["/th/product/x-tek-40-donut-wing", "/th/store/category/equipment/"],
  ["/th/reel-guideline", "/th/posts/tips-and-tricks/reel-guideline/"],
  ["/th/refund-policy", "/th/refund-policy/"],
  ["/th/scuba-diving-beginner-guide", "/th/posts/koh-chang-diving-travel-guides/beginner-guide/"],
  ["/th/smb-guide", "/th/posts/scuba-knowledge/smb-guide/"],
  ["/th/store", "/th/store/"],
  ["/th/store/category/courses", "/th/store/category/courses/"],
  ["/th/store/category/courses/advanced-courses", "/th/store/category/courses/advanced-courses/"],
  ["/th/store/category/courses/beginner-courses", "/th/store/category/courses/beginner-courses/"],
  ["/th/store/category/courses/professional-courses", "/th/store/category/courses/professional-courses/"],
  ["/th/store/category/courses/speciality", "/th/store/category/courses/speciality/"],
  ["/th/store/category/courses/technical-diving-courses", "/th/store/category/courses/technical-diving-courses/"],
  ["/th/store/category/day-trips", "/th/store/category/day-trips/"],
  ["/th/store/category/equipment", "/th/store/category/equipment/"],
  ["/th/sustainable-diving", "/th/posts/straight-talk/sustainable-diving/"],
  ["/th/terms-and-conditions", "/th/terms-and-conditions/"],
  ["/th/thailand-diving-comparison", "/th/posts/koh-chang-diving-travel-guides/thailand-diving-comparison/"],
  ["/th/the-best-dive-computers-2025", "/th/posts/scuba-knowledge/best-dive-computers/"],
  ["/th/the-dive-logbook", "/th/posts/scuba-knowledge/dive-logbook/"],
  ["/th/titan-triggerfish-koh-chang", "/th/posts/marine-life-koh-chang/marine-life-titan-triggerfish/"],
  ["/th/travel-guide", "/th/posts/koh-chang-diving-travel-guides/travel-guide/"],
  ["/th/videos", "/th/videos/"],
  ["/th/walhaie-auf-koh-chang-eine-begegnung-der-besonderen-art", "/th/posts/marine-life-koh-chang/marine-life-whale-shark/"],
  ["/th/weather", "/th/weather/"],
  ["/th/which-course", "/th/posts/tips-and-tricks/which-course/"],
  // weitere paare hier … ["/de/alt", "/de/neu/"],
];


// 2) PREFIX/WILDCARD 301 — als Objekte { from, to }
//    wirkt wie /from/* -> /to/:splat
const REDIRECTS_PREFIX_RAW = [
  // BEISPIELE (kannst du erweitern):
  // { from: "/th/store/category/equipment/bcds",   to: "/th/store/category/equipment/" },
   { from: "/th/store/category/dcth", to: "/th/store/category/courses/" },
   { from: "/th/store/category/equipment/bcds", to: "/th/store/category/equipment/" },
   { from: "/th/store/category/equipment/fins", to: "/th/store/category/equipment/" },
   { from: "/th/store/category/equipment/masks", to: "/th/store/category/equipment/" },
   { from: "/th/store/category/equipment/regulator", to: "/th/store/category/equipment/" },
   { from: "/th/store/category/equipment/wetsuits", to: "/th/store/category/equipment/" },
   { from: "/th/2018/07", to: "/th/posts/" },
   { from: "/th/2019/11", to: "/th/posts/" },
   { from: "/th/ds", to: "/th/dive-sites/" },
   { from: "/th/%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%84%E0%B9%89%E0%B8%B2", to: "/th/" },
   { from: "/th/%E0%B8%A7%E0%B8%B4%E0%B8%94%E0%B8%B5%E0%B9%82%E0%B8%AD", to: "/th/videos/" },
   { from: "/th/%E0%B8%AB%E0%B8%A1%E0%B8%A7%E0%B8%94%E0%B8%AB%E0%B8%A1%E0%B8%B9%E0%B9%88", to: "/th/posts/" },
   { from: "/th/%E0%B9%80%E0%B8%81%E0%B8%B5%E0%B9%88%E0%B8%A2%E0%B8%A7%E0%B8%81%E0%B8%B1%E0%B8%9A%E0%B9%80%E0%B8%A3%E0%B8%B2", to: "/th/about/" },
   { from: "/th/%E0%B8%84%E0%B8%B3%E0%B8%96%E0%B8%B2%E0%B8%A1%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%9E%E0%B8%9A%E0%B8%9A%E0%B9%88%E0%B8%AD%E0%B8%A2", to: "/th/faqs/" },
   { from: "/th/%E0%B9%80%E0%B8%81%E0%B8%B5%E0%B9%88%E0%B8%A2%E0%B8%A7%E0%B8%81%E0%B8%B1%E0%B8%9A%E0%B9%80%E0%B8%A3%E0%B8%B2-%E0%B8%A8%E0%B8%B9%E0%B8%99%E0%B8%A2%E0%B9%8C%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89", to: "/th/about/" },
   { from: "/en/team", to: "/en/about/" },
   { from: "/en/store/category/equipment/bcds", to: "/en/store/category/equipment/" },
   { from: "/en/store/category/equipment/regulator", to: "/en/store/category/equipment/" },
   { from: "/%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%84%E0%B9%89%E0%B8%B2", to: "/th/" },
   { from: "/de/category", to: "/de/posts/" },
   { from: "/de/Kategorie", to: "/de/posts/" },
   { from: "/de/store/category/equipment/atemregler", to: "/de/store/category/equipment/" },
   { from: "/de/store/category/equipment/bcds", to: "/de/store/category/equipment/" },
   { from: "/de/store/category/equipment/tarierjackets", to: "/de/store/category/equipment/" },
   { from: "/de/store/category/equipment/taschen-rucksaecke", to: "/de/store/category/equipment/" },
   { from: "/de/store/category/equipment/tauchzubehoer", to: "/de/store/category/equipment/" },
   { from: "/de/store/category/equipment/fins", to: "/de/store/category/equipment/" },
   { from: "/de/store/category/equipment/flossen", to: "/de/store/category/equipment/" },
   { from: "/de/store/category/equipment/masken", to: "/de/store/category/equipment/" },
   { from: "/de/store/category/equipment/masks", to: "/de/store/category/equipment/" },
   { from: "/de/store/category/equipment/neopren", to: "/de/store/category/equipment/" },
   { from: "/de/store/category/equipment/regulator", to: "/de/store/category/equipment/" },
   { from: "/de/store/category/equipment/wetsuits", to: "/de/store/category/equipment/" },
   { from: "/de/store/category/packages", to: "/de/store/category/equipment/" },
   { from: "/de/store/category/tages-ausfluege", to: "/de/store/category/day-trips/" },
   { from: "/de/store/category/tauchkurse", to: "/de/store/category/courses/" },
   { from: "/de/store/tages-ausfluege", to: "/de/store/category/day-trips/" },
   { from: "/de/store/tauch-kurse", to: "/de/store/category/courses/" },
   { from: "/de/store/tauch-packete", to: "/de/store/category/courses/" },
   { from: "/de/store/tauchausruestung", to: "/de/store/category/equipment/" },
   { from: "/de/store/tauchkurse", to: "/de/store/category/courses/" },
   { from: "/de/tauchpl%C3%A4tze", to: "/de/dive-sites/" },
   { from: "/de/team", to: "/de/about/" },
   { from: "/de/ueber-uns-chang-diving-center-koh-chang-thailand", to: "/de/about/" },
   { from: "/de/ueber-uns", to: "/de/about/" },
   { from: "/de/videos", to: "/de/videos/" },
   { from: "/en/category", to: "/en/posts/" },
   { from: "/th/%E0%B8%88%E0%B8%B8%E0%B8%94%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3", to: "/th/dive-sites/" },
];

// In Maps/normalisierte Regeln umwandeln
const REDIRECTS_EXACT = new Map(
  REDIRECTS_EXACT_RAW
    .map(([from, to]) => [normPath(ensureLeadingSlash(from)), ensureLeadingSlash(to)])
    // Selbst-Redirects rausfiltern:
    .filter(([from, to]) => from !== normPath(to))
);

const REDIRECTS_PREFIX = REDIRECTS_PREFIX_RAW
  .map(({ from, to }) => ({ from: normPath(ensureLeadingSlash(from)), to: ensureLeadingSlash(to) }))
  // Selbst-Redirects entfernen
  .filter(({ from, to }) => from !== normPath(to));

// --------------------- 410 GONE LISTEN ---------------------
// 3) EXAKTE 410 — als Set (Strings). Vollständig URL-encodiert eintragen.
const FORCE_GONE_EXACT = new Set(
  [
    // Beispiele:
   "/de/about/boots-plan",
   "/de/about/die-anmeldung",
   "/de/about/the-dive-process",
   "/de/nationalparks-in-thailand-und-koh-chang",
   "/de/natuerlich-haben-wir-schon-wracks-betaucht",
   "/de/product/privat-dive-boat",
   "/de/product/privates-tauchboot-tech",
   "/de/product/scuba-promotions",
   "/de/store/category/packages",
   "/de/store/category/privat-boat",
   "/de/store/category/privates-boot",
   "/en/apeks-dst4",
   "/en/apeks-xtx",
   "/en/forms",
   "/en/nationalparks-in-thailand-and-koh-chang",
   "/en/product/privat-dive-boat-tech",
   "/en/product/privat-dive-boat",
   "/en/product/scuba-promotions",
   "/en/service-technician",
   "/en/store/category/packages/covid-19-koh-chang",
   "/th/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%A3%E0%B8%AD%E0%B8%81%E0%B9%80%E0%B8%8A%E0%B8%B7%E0%B8%AD%E0%B8%81-%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B9%80%E0%B8%8A%E0%B8%B7%E0%B8%AD%E0%B8%81",
   "/th/%E0%B8%8B%E0%B8%B2%E0%B8%81%E0%B9%80%E0%B8%A3%E0%B8%B7%E0%B8%AD%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%99%E0%B9%88%E0%B8%B2%E0%B8%97%E0%B8%B6%E0%B9%88%E0%B8%87%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B9%80%E0%B8%81",
   "/th/%E0%B8%94%E0%B8%B2%E0%B8%A7%E0%B8%99%E0%B9%8C%E0%B9%82%E0%B8%AB%E0%B8%A5%E0%B8%94%E0%B9%81%E0%B8%9A%E0%B8%9A%E0%B8%9F%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%A1%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%88%E0%B8%B3",
   "/th/%E0%B8%9B%E0%B8%A3%E0%B8%B4%E0%B8%A1%E0%B8%B2%E0%B8%93%E0%B8%AD%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%A8%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%AB%E0%B8%B2%E0%B8%A2%E0%B9%83%E0%B8%88",
  "/th/%E0%B8%9E%E0%B8%A2%E0%B8%B2%E0%B8%81%E0%B8%A3%E0%B8%93%E0%B9%8C%E0%B8%AA%E0%B8%A0%E0%B8%B2%E0%B8%9E%E0%B8%AD%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%A8%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B9%80%E0%B8%81%E0%B8%B2",
  "/th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3%E0%B8%93%E0%B8%B2%E0%B8%93%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B9%81%E0%B8%9A%E0%B8%9A%E0%B9%84%E0%B8%AB%E0%B8%99%E0%B8%97%E0%B8%B5%E0%B9%88/",
  "/th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3%E0%B8%93%E0%B8%B2%E0%B8%93%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B9%81%E0%B8%9A%E0%B8%9A%E0%B9%84%E0%B8%AB%E0%B8%99%E0%B8%97%E0%B8%B5%E0%B9%88",
  "/th/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3%E0%B8%93%E0%B8%B2%E0%B8%93%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B9%81%E0%B8%9A%E0%B8%9A%E0%B9%84%E0%B8%AB%E0%B8%99%E0%B8%97%E0%B8%B5%E0%B9%88",
  "/th/%E0%B8%AD%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%A8%E0%B8%9C%E0%B8%AA%E0%B8%A1%E0%B8%9E%E0%B8%B4%E0%B9%80%E0%B8%A8%E0%B8%A9%E0%B9%84%E0%B8%99%E0%B8%95%E0%B8%A3%E0%B8%AD%E0%B8%81-%E0%B8%84%E0%B8%B7%E0%B8%AD",
  "/th/%E0%B8%AD%E0%B8%B8%E0%B8%97%E0%B8%A2%E0%B8%B2%E0%B8%99%E0%B9%81%E0%B8%AB%E0%B9%88%E0%B8%87%E0%B8%8A%E0%B8%B2%E0%B8%95%E0%B8%B4",
  "/th/%E0%B9%80%E0%B8%9E%E0%B8%B4%E0%B9%88%E0%B8%A1%E0%B8%AD%E0%B8%B8%E0%B8%94%E0%B8%A1%E0%B8%97%E0%B8%A3%E0%B8%B1%E0%B8%9E%E0%B8%A2%E0%B9%8C-%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89",
  "/th/%E0%B9%80%E0%B8%A3%E0%B8%B2%E0%B8%AA%E0%B8%AD%E0%B8%99%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3-%E0%B8%AD%E0%B8%A2%E0%B9%88%E0%B8%B2%E0%B8%87%E0%B9%84%E0%B8%A3",
  "/th/%E0%B9%80%E0%B8%AD%E0%B8%81%E0%B8%AA%E0%B8%B2%E0%B8%A3%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%88%E0%B8%B3%E0%B9%80%E0%B8%9B%E0%B9%87%E0%B8%99%E0%B8%AA%E0%B8%B3%E0%B8%AB%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%99",
  "/th/%E0%B9%81%E0%B8%9C%E0%B8%99%E0%B8%89%E0%B8%B8%E0%B8%81%E0%B9%80%E0%B8%89%E0%B8%B4%E0%B8%99%E0%B8%AA%E0%B8%B3%E0%B8%AB%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%AD%E0%B8%B8%E0%B8%9A%E0%B8%B1%E0%B8%95%E0%B8%B4",
  "/th/%E0%B9%83%E0%B8%8A%E0%B9%88-%E0%B9%80%E0%B8%A3%E0%B8%B2%E0%B9%80%E0%B8%84%E0%B8%A2%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%8B%E0%B8%B2%E0%B8%81%E0%B9%80%E0%B8%A3%E0%B8%B7%E0%B8%AD%E0%B8%88",
  "/th/%E0%B9%83%E0%B8%8A%E0%B9%88-%E0%B9%80%E0%B8%A3%E0%B8%B2%E0%B9%80%E0%B8%84%E0%B8%A2%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%8B%E0%B8%B2%E0%B8%81%E0%B9%80%E0%B8%A3%E0%B8%B7%E0%B8%AD%E0%B8%88",
  "/th/cdc-b",
  "/th/cdc-smb",
  "/th/cdc-w",
  "/th/cdc",
  "/th/cdc/%E0%B8%95%E0%B8%B2%E0%B8%A3%E0%B8%B2%E0%B8%87%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%93%E0%B8%B2%E0%B8%93%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3",
  "/th/cdc/%E0%B8%9A%E0%B8%A3%E0%B8%B4%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%93%E0%B8%B2%E0%B8%A3%E0%B8%93%E0%B8%B2%E0%B8%93%E0%B8%B3%E0%B8%99%E0%B9%89%E",
  "/th/fun-diving-koh-chang-%E0%B8%A7%E0%B8%B4%E0%B8%98%E0%B8%B5%E0%B8%81%E0%B8%B2%E0%B8%A3-2025",
  "/th/product-category/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3%E0%B8%93%E0%B8%B2%E0%B8%93%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3",
  "/th/product/%E0%B8%AA%E0%B8%84%E0%B8%B9%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%A3%E0%B8%B5%E0%B8%A7%E0%B8%B4%E0%B8%A7-%E0%B8%97%E0%B8%9A%E0%B8%97%E0%B8%A7%E0%B8%99%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%94%E0%B8%B3%E0%B8%99",
  "/th/product/%E0%B8%AA%E0%B8%84%E0%B8%B9%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%A3%E0%B8%B5%E0%B8%A7%E0%B8%B4%E0%B8%A7-%E0%B8%97%E0%B8%9A%E0%B8%97%E0%B8%A7%E0%B8%99%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%94%E0%B8%B3%E0%B8%99",
  "/th/product/%E0%B8%AA%E0%B8%AD%E0%B8%9A%E0%B9%80%E0%B8%9B%E0%B8%A5%E0%B8%B5%E0%B9%88%E0%B8%A2%E0%B8%99%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%9A%E0%B8%B1%E0%B8%99%E0%B8%AA%E0%B8%AD%E0%B8%99%E0%B8%84%E0%B8%A3%E0%B8%B9",
  "/th/product/%E0%B8%AA%E0%B8%AD%E0%B8%9A%E0%B9%80%E0%B8%9B%E0%B8%A5%E0%B8%B5%E0%B9%88%E0%B8%A2%E0%B8%99%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%9A%E0%B8%B1%E0%B8%99%E0%B8%AA%E0%B8%AD%E0%B8%99%E0%B8%84%E0%B8%A3%E0%B8%B9",
  "/th/product/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%AD%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%A8%E0%B8%9C%E0%B8%AA%E0%B8%A1",
  "/th/product/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%AD%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%A8%E0%B8%9C%E0%B8%AA%E0%B8%A1",
  "/th/product/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3%E0%B8%93%E0%B8%B2%E0%B8%93%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%81%E0%B8%A5%E0%B8%B2%E0%B8%87%E0%B8%84%E0%B8%B7%E0%B8%99",
  "/th/product/%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3%E0%B8%93%E0%B8%B2%E0%B8%93%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%81%E0%B8%A5%E0%B8%B2%E0%B8%87%E0%B8%84%E0%B8%B7%E0%B8%99",
  "/th/product/%E0%B9%80%E0%B8%8A%E0%B9%88%E0%B8%B2-%E0%B9%80%E0%B8%AB%E0%B8%A1%E0%B8%B2%E0%B9%80%E0%B8%A3%E0%B8%B7%E0%B8%AD-%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%A5%E0%B8%B6%E0%B8%81-%E0%B8%95",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%8A%E0%B9%88%E0%B8%A7%E0%B8%A2%E0%B8%8A%E0%B8%B5%E0%B8%A7%E0%B8%B4%E0%B8%95%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%9B%E0%B8%90",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%8A%E0%B9%88%E0%B8%A7%E0%B8%A2%E0%B8%8A%E0%B8%B5%E0%B8%A7%E0%B8%B4%E0%B8%95%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%9B%E0%B8%90",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%84%E0%B8%A3%E0%B8%B9%E0%B8%9C%E0%B8%B9%E0%B9%89%E0%B8%AA%E0%B8%AD%E0%B8%99%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%8A%E0%B9%88%E0%B8%A7%E0%B8%A2%E0%B8%8A",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%84%E0%B8%A3%E0%B8%B9%E0%B8%9C%E0%B8%B9%E0%B9%89%E0%B8%AA%E0%B8%AD%E0%B8%99%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%8A%E0%B9%88%E0%B8%A7%E0%B8%A2%E0%B8%8A",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%8A%E0%B9%88%E0%B8%A7%E0%B8%A2%E0%B9%80%E0%B8%AB%E0%B8%A5%E0%B8%B7%E0%B8%AD%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%9E%E0%B8%B4%E0%B9%80%E0%B8%A8%E0%B8%A9-%E0%B8%95%E0%B8%B4%E0%B8%94%E0%B8%96",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%9E%E0%B8%B4%E0%B9%80%E0%B8%A8%E0%B8%A9-%E0%B8%95%E0%B8%B4%E0%B8%94%E0%B8%96",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%A5%E0%B8%B6%E0%B8%81%E0%B8%84%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%AA%E0%B9%80%E0%B8%A3%E0",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%A5%E0%B8%B6%E0%B8%81%E0%B8%84%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%AA%E0%B9%80%E0%B8%A3%E0",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%A5%E0%B8%B6%E0%B8%81%E0%B8%84%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%AA%E0%B9%80%E0%B8%A3%E0",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%A5%E0%B8%B6%E0%B8%81%E0%B8%84%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%AA%E0%B9%80%E0%B8%A3%E0",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%A5%E0%B8%B6%E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B8%94%E0%B8%B1%E0%B8%9A%E0%B8%AA%E0%B8%B9%E0",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%94%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B9%80%E0%B8%97%E0%B8%84%E0",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%94%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B9%80%E0%B8%97%E0%B8%84%E0",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%94%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B9%80%E0%B8%97%E0%B8%84%E0",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%94%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B9%80%E0%B8%97%E0%B8%84%E0",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%94%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B9%80%E0%B8%97%E0%B8%84%E0",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%94%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B9%80%E0%B8%97%E0%B8%84%E0",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%A5%E0%B8%B6%E0%B8%8140%E0%B9%80%E0%B8%A1%E0%B8%95%E0%B8%A3",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%AA%E0%B8%B3%E0%B8%A3%E0%B8%A7%E0%B8%88%E0%B9%80%E0%B8%A3%E0",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0%B8%B3%E0%B8%AA%E0%B8%B3%E0%B8%A3%E0%B8%A7%E0%B8%88%E0%B9%80%E0%B8%A3%E0",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0",
  "/th/product/%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%81%E0%B8%AA%E0%B8%B9%E0%B8%95%E0%B8%A3%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B3%E0%B8%99%E0%B9%89%E0",
  "/th/product/dtin",
  "/th/product/fd1",
  "/th/product/fd12",
  "/th/product/fd14",
  "/th/product/fd9",
  "/th/product/scuba-review-%E0%B8%84%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%AA%E0%B8%A3%E0%B8%B5%E0%B9%80%E0%B8%9F%E0%B8%A3%E0%B8%8A%E0%B8%AA%E0%B8%B3%E0%B8%AB%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%99%E0%B8%B1",
  "/th/store/category/courses/dcadth",
  "/th/store/category/courses/dcspth",
  "/th/store/category/dtb",
  "/th/store/category/dtp/%E0%B9%82%E0%B8%84%E0%B8%A7%E0%B8%B4%E0%B8%94-19-%E0%B9%80%E0%B8%81%E0%B8%B2%E0%B8%B0%E0%B8%8A%E0%B9%89%E0%B8%B2%E0%B8%87",
  "/th/store/category/dtth",
  "/th/store/category/packages",
  "/th/store/category/privat-boat",
  "/th/why-advanced",
    // weitere exakte 410er hier …
  ].map(p => normPath(ensureLeadingSlash(p)))
);

// 4) PREFIX 410 — alles darunter Gone (Strings)
const FORCE_GONE_PREFIX = [
     "/de/store/page",
     "/de/store/seite",
     "/de/store/tag",
     "/th/store/tag",
     "/th/%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%84%E0%B9%89%E0%B8%B2",
     "/en/tag",
     "/en/store/page",
     "/en/store/tag",
     "/de/store/kategorie",
     "/de/tag",
     "/en/en",
     "/de/de",
     "/th/th",
  // ggf. weitere Präfixe …
].map(p => normPath(ensureLeadingSlash(p)));

function findPrefixRule(path, rules) {
  for (const from of rules) {
    if (path === from || path.startsWith(from + "/")) return from;
  }
  return null;
}

function findPrefixRedirect(path, rules) {
  for (const { from, to } of rules) {
    if (path === from || path.startsWith(from + "/")) {
      const rest = path.slice(from.length); // "" oder "/…"
      return joinUrl(to, rest);
    }
  }
  return null;
}

function withDebug(res, tag) {
  const h = new Headers(res.headers || {});
  if (!h.has("X-Debug")) h.set("X-Debug", tag);
  return new Response(res.body, { status: res.status, headers: h });
}

export async function onRequest(context) {
  const url = new URL(context.request.url);
  const path = normPath(url.pathname);

  // --- 1) 301 EXAKT ---
  if (REDIRECTS_EXACT.has(path)) {
    const location = REDIRECTS_EXACT.get(path);
    return new Response(null, { status: 301, headers: { Location: location, "X-Debug": "301-exact" } });
  }

  // --- 2) 301 PREFIX/WILDCARD ---
  const loc = findPrefixRedirect(path, REDIRECTS_PREFIX);
  if (loc) {
    return new Response(null, { status: 301, headers: { Location: loc, "X-Debug": "301-prefix" } });
  }

  // --- 3) statische ausliefern lassen ---
  const res = await context.next();
  if (res.status !== 404) return withDebug(res, "pages-pass");

  // --- 4) Wenn 404: 410 EXAKT ---
  if (FORCE_GONE_EXACT.has(path)) {
    return new Response("410 Gone", { status: 410, headers: { "X-Debug": "410-exact" } });
  }

  // --- 5) 410 PREFIX ---
  if (findPrefixRule(path, FORCE_GONE_PREFIX)) {
    return new Response("410 Gone", { status: 410, headers: { "X-Debug": "410-prefix" } });
  }

  // --- 6) Global: alles außerhalb Sprachpfade & nicht-Assets -> 410 ---
  if (!isInLang(path) && !isAsset(path)) {
    return new Response("410 Gone", { status: 410, headers: { "X-Debug": "410-global" } });
  }

  // Sprachpfad 404 bleibt 404 (echter Tippfehler in gültiger Sprache)
  return withDebug(res, "404-in-lang");
}